<script>
    function alertaFechaSystem(){
    
     $('#divAlertaFecha').delay( 10 ).fadeIn( 500 );
            $('#divAlertaFecha').animate({
                    'display': 'block'
            });
            
            $('#divAlertaFecha').delay( 2000 ).fadeOut( 500 );
            $('#divAlertaFecha').animate({
                                        'display': 'none'
                                    });

    
}
    </script>

<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">
            <h1>Bienvenido!</h1>
        </div>
        
       <?php if(Session::get('sess_error_fechas'))
        { ?>
       
        <div id="divAlertaFecha" class="alert alert-dismissable alert-warning" style="display:none; margin: 5px;">
                                No se encontraron registros para esta busqueda.
                            </div>
        <script type="text/javascript">alertaFechaSystem(); </script>
        
       <?php
        Session::destroy('sess_error_fechas');
       
        } ?>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-danger">


                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h4>Estas son algunas de nuestras &uacute;ltimas ofertas.</h4>
                            </div>
                            <div class="panel-body">
                                <div class="row">

                                    <div class="col-md-12">
                                        <center>
                                            
                                            <!-- SLIDER -->
                                            <iframe src="http://www.panamericanaturismo.cl/newsite/main_campanas_frame.asp" frameborder="0" width="750" height="320" scrolling="no"></iframe>
                                            <!-- END: SLIDER -->
                                            
                                        </center>
                                    </div>

                                </div>
                            </div>
                        </div>	





                    </div>
                </div>
            </div>
        </div>

    </div> <!--wrap -->
</div> <!-- page-content -->

