<center>
    <span style='font-weight: bold;'>CONDICIONES GENERALES</span>
</center>
<br />
<ul type='disc'>
    <li>Los precios publicados son por persona e incluyen solo lo especificado en cada programa. Los servicios no utilizados no ser&aacute;n reembolsables.</li>
    <li>Los pasajes a&eacute;reos NO tienen devoluci&oacute;n y NO permiten cambios de fecha, nombre, g&eacute;nero ni rut.</li>
    <li>Los cargos a&eacute;reos son parte del valor del programa, por lo tanto no tienen devoluci&oacute;n en caso de anulaci&oacute;n. Se encuentran sujetos a variaci&oacute;n por parte de la cia. a&eacute;rea, &eacute;stos se congelan solamente con el pago total del viaje.  Las tasas de embarque son determinadas por las autoridades competentes y pueden variar su valor.</li>
    <li>Los gastos de anulaci&oacute;n de servicios terrestres, quedan supeditados a las pol&iacute;ticas de los distintos hoteles y proveedores tur&iacute;sticos involucrados en cada uno de los programas.  En per&iacute;odos de alta temporada ( enero, febrero, julio), el costo de la anulaci&oacute;n corresponde al total de la estad&iacute;a.</li>
    <li>Las habitaciones triples en algunos destinos y hoteles est&aacute;n compuestas por 2 camas matrimoniales, lo que obliga a compartir dichas camas.</li>
    <li>Los horarios de check in y check out son fijados por cada hotel.  En general las habitaciones est&aacute;n disponibles para su ingreso a partir de las 15:00 hrs y la salida debe ser antes de las 12:00 PM. Las salidas posteriores pueden significar cobros adicionales.</li>
    <li>Es obligaci&oacute;n del pasajero contar con la documentaci&oacute;n de viaje al d&iacute;a (C&eacute;dula de identidad, pasaportes, visados, autorizaciones notariales, etc.) y de cualquier otro requisito necesarios para ingresar al lugar de destino ya sea adulto o menor.</li>
    <li>Si por motivos externos a la responsabilidad de Panamericana tales como: condiciones clim&aacute;ticas, sismos, problemas pol&iacute;ticos, etc. obligue a modificar el programa y esto implique costos adicionales, &eacute;stos deben ser asumidos por cuenta del pasajero. En caso que el cliente no acepte los cargos adicionales y/o cambios de itinerario, los servicios ya contratados no tendr&aacute;n derecho a devoluci&oacute;n.</li>
    <li>Panamericana Turismo declina toda responsabilidad por cancelaciones, atrasos, cambios de horarios y de fecha determinados por las aerol&iacute;neas.</li>
</ul>