<script>
    $('.blink').each(function () {
        var elem = $(this);
        setInterval(function () {

            elem.animate({opacity: 0}, 400);
            elem.animate({opacity: 1}, 400);

        }, 1000);
    });
</script>





<div class="panel panel-primary" id="DP_principal" style="display: block;">
    <div class="panel-heading">

        <?php
        Session::set('sess_nombrePrograma', $this->objProgramas[0]->getTitulo());
        Session::set('sess_ciudadPrograma', $this->objProgramas[0]->getCiudad());
        Session::set('sess_codigoPrograma', $this->objProgramas[0]->getCodigo());

        echo $this->objProgramas[0]->getTitulo(); // . ' - ' . $this->objProgramas[0]->getCodigo(); 
        ?>

        <div class="options">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#tarifas" data-toggle="tab">Incluye</a>
                </li>
                <li>
                    <a href="#descripcion" data-toggle="tab">Descripci&oacute;n</a>
                </li>
                <li>
                    <a href="#condiciones" data-toggle="tab">Condiciones</a>
                </li>
            </ul>
        </div>

    </div>




    <div class="panel-body">
        <div class="tab-content">





            <div class="tab-pane active" id="tarifas" >
                <div>

                    <table width="100%"  style="margin-top: -15px; margin-left: -15px;">
                        <tr>
                            <td colspan="2">
                                <P style="font-size:11px">
                                    <b style="color:#FF9900;">PAIS:</b> <?php echo $this->objProgramas[0]->getPais(); ?>, 
                                    <b style="color:#FF9900; margin-left: 10px;">CIUDAD:</b> <?php echo $this->objProgramas[0]->getCiudad(); ?> 
                                    <label style="margin-right: 30px;">&nbsp;</label>
                                    <?php if ($this->objProgramas[0]->getPbhotel()) { ?><img name="tooltip_pro" src="<?php echo $_layoutParamsCB['ruta_img']; ?>hotel_ico.jpg" width="16" style="margin-left:5px;" title="Hotel">  <?php } ?>
                                    <?php if ($this->objProgramas[0]->getPdtraslados()) { ?><img name="tooltip_pro" src="<?php echo $_layoutParamsCB['ruta_img']; ?>transfer_ico.jpg" width="16" style="margin-left:5px;" title="Traslado">  <?php } ?>
                                    <?php if ($this->objProgramas[0]->getPdaereo()) { ?><img name="tooltip_pro" src="<?php echo $_layoutParamsCB['ruta_img']; ?>avion_ico.jpg" width="16" style="margin-left:5px;" title="Aereo"><?php } ?>
                                    <?php if ($this->objProgramas[0]->getPdseguro()) { ?><img name="tooltip_pro" src="<?php echo $_layoutParamsCB['ruta_img']; ?>seguro_ico.jpg" width="16" style="margin-left:5px;" title="Seguro">  <?php } ?>
                                    <?php if ($this->objProgramas[0]->getPdplana()) { ?><img name="tooltip_pro" src="<?php if($this->objProgramas[0]==='Desayuno'){ echo $_layoutParamsCB['ruta_img']; ?>desayuno_ico.jpg<?php }else{ echo $_layoutParamsCB['ruta_img']; ?>comida_ico.jpg<?php } ?>" width="16" style="margin-left:5px;" title="<?php echo $this->objProgramas[0]->getPdplana();?>">  <?php } ?>
                                </P>
                            </td>
                        </tr>
                        <tr>
                            <td width="210" valign="top">
                                <?php if ($this->objProgramas[0]->getImagen()) { ?>
                                    <img src="<?php echo $_layoutParamsCB['ruta_programas'] . $this->objProgramas[0]->getImagen(); ?>" width="200" class="img-thumbnail" style="margin-right: 10px;">
                                <?php } else {
                                    ?>
                                    <img src="<?php echo $_layoutParamsCB['ruta_programas']; ?>sin_foto.png" width="150" class="img-thumbnail" style="margin-right: 10px;">
                                <?php } ?>
                            </td>
                            <td>
                                <b style="color:#FF9900;">INCLUYE:</b> <br>
                                <img  src="<?php echo $_layoutParamsCB['ruta_img']; ?>tick.png" width="12px" /> <?php echo substr(str_replace("<span style='color:#008ccc;'>&bull;</span>", '<img src="' . $_layoutParamsCB['ruta_img'] . 'tick.png" width="12px" />', $this->objProgramas[0]->getIncluye()), 0, -95); ?>

                                <?php if ($this->_PDF) { ?>
                                    <a id="btnDP_itinerario" class="btn btn-info btn-sm" onclick="fadeIn('detallePopup');
                                            $('#divPopupIn').css('overflow-y', 'hidden');
                                            abrePopup('divPopupIn', '<?php echo BASE_URL; ?>programas/itinerario', 'tituloPopup', 'Itinerario', '<?php echo $this->objProgramas[0]->getCodigo(); ?>');" style="width: 88px; float: right;" >Itinerario</a>
<?php } ?>
                            </td>
                        </tr>
                    </table>

                </div>

            </div>






            <div class="tab-pane" id="descripcion">
                <table width="100%" style="margin-top: -15px; margin-left: -15px;">
                    <tr>
                        <td colspan="2">
<?php echo $this->objProgramas[0]->getDescrip(); ?>
                        </td>
                    </tr>
                </table>
            </div>






            <div class="tab-pane" id="condiciones">
                <table width="100%" style="margin-top: -15px; margin-left: -15px;">
                    <tr>
                        <td colspan="2">
                            <p>
<?php echo $this->objProgramas[0]->getNota(); ?>
                            </p>
                        </td>
                    </tr>

                </table>
            </div>
        </div>
    </div>

    <input type="hidden" id="ValiFormLogin" value="<?php if (!Session::get('Autenticado')) {
    echo'0';
} else {
    echo'1';
} ?>">





    <?php
    if ($this->objOpcProgramas) {
        $cntDP = 1;
        foreach ($this->objOpcProgramas as $objOpcProg) {

            $DP_hoteles = $objOpcProg->getNombreHotel();
            $DP_cod_hoteles = $objOpcProg->getCodHotel();
            $DP_dirHot = $objOpcProg->getDir();
            $DP_catHot = $objOpcProg->getCat();
            $DP_thHot = $objOpcProg->getTipoHab();
            $DP_codthHot = $objOpcProg->getCodTH();
            $DP_planAl = $objOpcProg->getPlanAl();
            $DP_cntHoteles = count($objOpcProg->getNombreHotel());
            ?>
            <br />
            <div class="panel-heading" style="margin-top: 20px;" >
                Opci&oacute;n <?php echo $cntDP;
        if ($objOpcProg->getEstado() == 'AVAILABLE') { ?>
                    <div style="float: right;"><div style=" position: absolute;"> <img style=" margin-top: -5px; margin-left: -47px; width: 51px;" src="<?php echo $_layoutParamsCB['ruta_img']; ?>icono_confirmar.png"></div><?php //echo $objOpcProg->getEstado();  ?></div>
        <?php } ?>
                <div style="float: right ;<?php if($objOpcProg->getEstado() == 'AVAILABLE'){ echo 'margin-right: 51px';} ?>">
                    <a data-toggle="modal" href="#myModal2" onclick="fadeIn('detallePopup');
                            $('#divPopupIn').css('overflow-y', 'scroll');
                            abrePopupImprimirProg('divPopupIn', '<?php echo BASE_URL; ?>programas/imprimir', 'tituloPopup2', 'Vista Previa',
                                                    <?php echo htmlspecialchars(json_encode($DP_thHot)); ?>,
                                                    <?php echo htmlspecialchars(json_encode($DP_hoteles)); ?>,
                                                    <?php echo htmlspecialchars(json_encode($DP_planAl)); ?>,
                                                    <?php echo htmlspecialchars(json_encode($DP_catHot)); ?>,
                                                    '<?php echo $objOpcProg->getIdOpc(); ?>',
                                                    '<?php echo $objOpcProg->getMoneda(); ?>',
                                                    '<?php echo $objOpcProg->getVVenSGL();?>',
                                                    '<?php echo $objOpcProg->getVVenDBL();?>',
                                                    '<?php echo $objOpcProg->getVVenTPL();?>',
                                                    '<?php echo $objOpcProg->getChd1(); ?>',
                                                    '<?php echo $objOpcProg->getChd2(); ?>',
                                                    '<?php echo $objOpcProg->getVVenPF()?>',
                                                    '<?php echo $this->form; ?>');">
                        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>print.png" border='0' height='20' title='Imprimir' width="24" style="margin-left:5px;"/>
                    </a>
                    <a href="#myModal2" data-toggle="modal" onclick="fadeIn('detallePopup');
                            $('#divPopupIn').css('overflow-y', 'scroll');
                            abrePopup('divPopupIn', '<?php echo BASE_URL; ?>bloqueos/notas', 'tituloPopup2', 'Nota de Programa', '<?php echo $objOpcProg->getIdOpc(); ?>', '<?php echo $this->form; ?>');" title='Nota opcion'><img src="<?php echo $_layoutParamsCB['ruta_img']; ?>nota.png" width="24" style="margin-left:5px;" ></a>
                </div>
            </div>
            <div class="panel-body">
                <div class="tab-content" style="display: block;" id="tab_content_1_<?php echo $cntDP; ?>">


                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" style="font-size:12px; width: 100%; margin-top: 20px;" align='center'> <!-- class="table table-striped table-bordered" -->
                        <thead>
                            <tr style="background-color:#34495e; color: #FFFFFF" role="row">
                                <th role="columnheader" style="padding-left: 2px;width: 122px; text-align: center;">Hotel</th>
                                <!--<th role="columnheader" style="padding-left: 2px; width: 300px;">Direcci&oacute;n</th>-->
                                <th role="columnheader" style="padding-left: 2px; width: 80px;text-align: center;" >Categoria</th>
                                <th role="columnheader" style="padding-left: 2px; width: 100px;text-align: center;" >Habitaci&oacute;n</th>
                                <th role="columnheader" style="padding-left: 2px; width: 100px;text-align: center;" >Plan Alimenticio</th>
                                <th role="columnheader" style="padding-left: 2px; width: 50px;text-align: center;"></th>
                                <th role="columnheader" style="padding-left: 2px; width: 50px;text-align: center;"></th>
                                <!--<th role="columnheader" style="padding-left: 2px; width: 50px;"></th>-->

                            </tr>
                        </thead>

                                <?php
                                for ($i = 0; $i < $DP_cntHoteles; $i++) {
                                    ?>
                            <tr>
                                <td style="color: #DF5F00; padding: 2px; vertical-align: middle;">
                                    <a id="tooltip_hotel_<?php echo $objOpcProg->getClaveOpc(); ?>"  data-toggle='modal' href='#myModal2' style="cursor:pointer"onClick="fadeIn('detallePopup');
                                            $('#divPopupIn').css('overflow-y', 'scroll');
                                            abrePopup('divPopupIn', '<?php echo BASE_URL; ?>bloqueos/servicios', 'tituloPopup2', '<?php echo $DP_hoteles[$i]; ?>', <?php echo $DP_cod_hoteles[$i] ?>, '<?php echo $this->form; ?>');"><?php echo $DP_hoteles[$i]; ?></a>
                                </td>
                                <!--<td style="padding: 2px; vertical-align: middle;"><?php echo $DP_dirHot[$i]; ?></td>-->
                                <td style="padding: 2px; vertical-align: middle;">
            <?php
            if (strlen($DP_catHot[$i]) == 2) {
                for ($j = 1; $j <= 5; $j++) {
                    if ($j <= substr($DP_catHot[$i], 0, 1)) {
                        ?>
                                                <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>star_on.png" height='12' title='Categoria' />
                    <?php } else { ?>
                                                <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>star_off.png" height='12' title='Categoria' />
                                            <?php
                                            }
                                        }
                                    } else {
                                        echo $DP_catHot[$i];
                                    }
                                    ?>
                                </td>

                                <td style="padding: 2px; vertical-align: middle; color: #0075b0;">
                                    <?php echo $DP_thHot[$i]; ?>
                                    <!--<a data-toggle='modal' href='#myModal2' 
                                       onClick="fadeIn('detallePopup');
                                               $('#divPopupIn').css('overflow-y', 'scroll');
                                               abrePopupHab('divPopupIn', '<?php echo BASE_URL; ?>bloqueos/fotosTipoHab', 'tituloPopup2', 'Fotos Tipo Habitaci&oacute;n', '<?php echo $DP_codthHot[$i]; ?>', <?php echo $DP_cod_hoteles[$i]; ?>, '<?php echo $this->form; ?>');">
                                    </a>-->
                                </td>
                                <td style="color: #0075b0; padding: 2px; vertical-align: middle;">
            <?php echo $DP_planAl[$i]; ?>
                                </td>
                                <td style="text-align: center;">
                                    <a data-toggle="modal" href="#myModal2" 
                                       onClick="fadeIn('detallePopup');
                                               $('#divPopupIn').css('overflow-y', 'scroll');
                                               abrePopup('divPopupIn', '<?php echo BASE_URL; ?>bloqueos/fotosHotel', 'tituloPopup2', 'Fotos Hotel', <?php echo $DP_cod_hoteles[$i]; ?>, '<?php echo $this->form; ?>');">
                                        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>foto.jpg" border='0' height='25' title='Fotos' />
                                    </a>
                                </td>
                                <td style="text-align: center;">
                                    <a data-toggle="modal" href="#myModal2" 
                                       onClick="fadeIn('detallePopup');
                                               $('#divPopupIn').css('overflow-y', 'scroll');
                                               abrePopup('divPopupIn', '<?php echo BASE_URL; ?>bloqueos/mapas', 'tituloPopup2', 'Google Maps', <?php echo $DP_cod_hoteles[$i]; ?>, '<?php echo $this->form; ?>');" >
                                        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>mapa.jpg" border='0' height='25' title='Mapa' />
                                    </a>
                                </td>
                                <!--<td>
                                    <a data-toggle='modal' href='#myModal' 
                                        onClick="fadeIn('detallePopup'); $('#divPopupIn').css('overflow-y', 'scroll'); abrePopup('divPopupIn', '<?php echo BASE_URL; ?>bloqueos/servicios', 'tituloPopup', '<?php echo $DP_hoteles[$i]; ?>', <?php echo $DP_cod_hoteles[$i] ?>,'<?php echo $this->form; ?>');">
                                        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>hotel.jpg" border='0' height='25' width="40" title='Hotel' />
                                    </a>
                                </td>-->
                            </tr>
            <?php }
        ?>
                    </table>



                    <!-- RESERVAR -->
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" align="center">
                        <tr>
                            <td style="font-size: 14px; text-align: center"> <b>SINGLE</b> </td>
                            <td style="font-size: 14px; text-align: center"> <b>DOBLE</b> </td>
                            <td style="font-size: 14px; text-align: center"> <b>TRIPLE </b></td>
                            <td style="font-size: 14px; text-align: center"> <b>CHILD 1</b></td>
                            <td style="font-size: 14px; text-align: center"> <b>CHILD 2 </b></td>
                            <td style="font-size: 14px; text-align: center"> <b>PLAN FAMILIAR </b></td>
                            <td style="font-size: 14px; text-align: center"> </td>
                        </tr>

                        <tr>
                            <td style="padding: 2px; vertical-align: middle;" align="center">
                                <label style="color: #DF5F00; font-weight: bold; font-size:19px; <?php if($this->pago && $objOpcProg->getMoneda() ==='D'){?>margin-bottom: -1px;<?php } ?>"><?php if($objOpcProg->getVVenSGL()==0){ echo '--'; }else{echo Functions::formatoValor($objOpcProg->getMoneda(), $objOpcProg->getVVenSGL());} ?>
                                </label><br>
                                <?php if( $this->pago && $objOpcProg->getMoneda() ==='D' && $objOpcProg->getVVenSGL()>0 ){?>
                                <b style=" font-size: 13px; color : #34495e;"><?php echo Functions::formatoValor('P',$objOpcProg->getVVenSGL() * Session::get('sess_tcambio'));?></b><br>
                                <?php }?>
                            </td>
                            <td style="padding: 2px; vertical-align: middle;" align="center">
                                <label style="color: #DF5F00; font-weight: bold; font-size:19px; <?php if($this->pago && $objOpcProg->getMoneda() ==='D'){?> margin-bottom: -1px; <?php } ?>"><?php if($objOpcProg->getVVenDBL()==0){ echo '--'; }else{ echo Functions::formatoValor($objOpcProg->getMoneda(), $objOpcProg->getVVenDBL());} ?></label>
                                <br>
                                <?php if($this->pago && $objOpcProg->getMoneda() ==='D' && $objOpcProg->getVVenDBL()>0){?>
                                <b style=" font-size: 13px; color : #34495e;"><?php echo Functions::formatoValor('P',$objOpcProg->getVVenDBL() * Session::get('sess_tcambio'));?></b><br>
                                <?php } ?>
                            </td>
                            <td style="padding: 2px; vertical-align: middle;" align="center">
                                <label style="color: #DF5F00; font-weight: bold; font-size:19px; <?php if($this->pago && $objOpcProg->getMoneda() ==='D'){?> margin-bottom: -1px; <?php } ?>"><?php if($objOpcProg->getVVenTPL()==0){ echo'--';}else{echo Functions::formatoValor($objOpcProg->getMoneda(), $objOpcProg->getVVenTPL());} ?></label>
                                <br>
                                <?php if($this->pago && $objOpcProg->getMoneda() ==='D' && $objOpcProg->getVVenTPL()>0){?>
                                <b style=" font-size: 13px; color : #34495e;"><?php echo Functions::formatoValor('P',$objOpcProg->getVVenTPL() * Session::get('sess_tcambio'));?></b><br>
                                <?php } ?>
                            </td>

                            <td style="padding: 2px; vertical-align: middle;" align="center">
                                <label style="color: #DF5F00; font-weight: bold; font-size:19px; <?php if($this->pago && $objOpcProg->getMoneda() ==='D' && $objOpcProg->getChd1() > 0){?>margin-bottom: -1px;<?php } ?>"><?php if ($objOpcProg->getChd1() == 0) {
                               echo "--";
                           } else {
                               echo Functions::formatoValor($objOpcProg->getMoneda(), $objOpcProg->getChd1());
                           } ?></label>
                                <br>
                                <?php if($this->pago && $objOpcProg->getMoneda() ==='D' && $objOpcProg->getChd1() > 0 ){?>
                                <b style=" font-size: 13px; color : #34495e;"><?php if ($objOpcProg->getChd1() > 0) { echo Functions::formatoValor('P',$objOpcProg->getChd1() * Session::get('sess_tcambio')); } ?></b><br>
                                <?php } ?>
                            </td>
                            <td style="padding: 2px; vertical-align: middle;" align="center">
                                <label style="color: #DF5F00; font-weight: bold; font-size:19px; <?php if($this->pago && $objOpcProg->getMoneda() ==='D' && $objOpcProg->getChd2() > 0){?> margin-bottom: -1px; <?php } ?>"><?php if ($objOpcProg->getChd2() == 0) {
                               echo "--";
                           } else {
                               echo Functions::formatoValor($objOpcProg->getMoneda(), $objOpcProg->getChd2());
                               } ?></label><br>
                               <?php if($this->pago && $objOpcProg->getMoneda() ==='D' && $objOpcProg->getChd2() > 0){?>
                               <b style=" font-size: 13px; color : #34495e;"><?php if ($objOpcProg->getChd2() > 0) { echo Functions::formatoValor('P',$objOpcProg->getChd2() * Session::get('sess_tcambio')); } ?></b><br>
                               <?php } ?>
                            </td>
                            <td style="padding: 2px; vertical-align: middle;" align="center">
                                <label style="color: #DF5F00; font-weight: bold; font-size:19px; <?php if($this->pago && $objOpcProg->getMoneda() ==='D' && $objOpcProg->getVVenPF() > 0 && $objOpcProg->getChd2() > 0&&$objOpcProg->getChd1() > 0){?> margin-bottom: -1px; <?php } ?>"><?php if ($objOpcProg->getVVenPF() == 0) {
                               echo "--";
                           } else {
                               echo Functions::formatoValor($objOpcProg->getMoneda(), $objOpcProg->getVVenPF());
                               } ?></label><br>
                               <?php if($this->pago && $objOpcProg->getMoneda() ==='D' && $objOpcProg->getVVenPF() > 0 ){?>
                               <b style=" font-size: 13px; color : #34495e;"><?php if ($objOpcProg->getVVenPF() > 0) { echo Functions::formatoValor('P',$objOpcProg->getVVenPF() * Session::get('sess_tcambio')); } ?></b><br>
                               <?php } ?>
                            </td>
                            <td style="padding: 2px; vertical-align: middle;" align="center">


                                <a id="btnDP_reservar_<?php echo $cntDP; ?>" class="btn btn-success btn-sm" style="width: 88px;"
                                   data-toggle="modal" href="#myModal2"
                                   onclick="Programa.prototype.abrirForm('<?php echo $cntDP; ?>',
                                                   '<?php echo BASE_URL; ?>programas/pasajeros',
                                                   '<?php echo $objOpcProg->getVVenSGL(); ?>',
                                                   '<?php echo $objOpcProg->getVVenDBL(); ?>',
                                                   '<?php echo $objOpcProg->getVVenTPL(); ?>',
                                                   '<?php echo $objOpcProg->getVVenPF(); ?>',
                                                   '<?php echo $objOpcProg->getMoneda(); ?>',
                                                   '<?php echo $objOpcProg->getClaveOpc(); ?>',
                                                   '<?php echo $this->form ?>',
                                                    <?php echo htmlspecialchars(json_encode($DP_thHot)); ?>,
                                                    <?php echo htmlspecialchars(json_encode($DP_hoteles)); ?>,
                                                    <?php echo htmlspecialchars(json_encode($DP_planAl)); ?>,
                                                    <?php echo htmlspecialchars(json_encode($DP_catHot)); ?>,
                                                   '<?php echo$objOpcProg->getChd1(); ?>',
                                                   '<?php echo$objOpcProg->getChd2(); ?>',
                                                   '<?php echo$objOpcProg->getEstado();?>',
                                                   <?php if($objOpcProg->getEstado() == 'AVAILABLE'){?>
                                                       'Reserva'
                                                     <?php }else{ ?>
                                                         'Cotizaci&oacute;n'
                                                     <?php } ?>
                                                   );"><?php if($objOpcProg->getEstado() == 'AVAILABLE'){?>
                                                                           RESERVAR
                                                   <?php }else{ ?> COTIZAR<?php } ?>
                                </a>
                            </td>
                        </tr>
                    </table>
                    <!-- END: RESERVAR -->

                </div>

            </div>

        <?php $cntDP++;
    }
} ?>


</div>
<script>
$(document).ready(function(){
    
    $("[name$='tooltip_pro']").poshytip({className: "tip-darkgray", alignY: "top"});
});
</script>





