<script>
    $('.blink').each(function() {
        var elem = $(this);
        setInterval(function() {
            
            elem.animate({opacity: 0}, 400);
            elem.animate({opacity: 1}, 400);
            
        }, 1000);
    });
</script>





<div class="panel panel-primary" id="DP_principal" style="display: block;">
    <div class="panel-heading">

        <?php
        Session::set('sess_nombrePrograma', $this->objProgramas[0]->getTitulo());
        Session::set('sess_ciudadPrograma', $this->objProgramas[0]->getCiudad());
        Session::set('sess_codigoPrograma', $this->objProgramas[0]->getCodigo());
        
        echo $this->objProgramas[0]->getTitulo(); // . ' - ' . $this->objProgramas[0]->getCodigo(); 
        ?>

        <div class="options">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#tarifas" data-toggle="tab">Incluye</a>
                </li>
                <li>
                    <a href="#descripcion" data-toggle="tab">Descripci&oacute;n</a>
                </li>
                <li>
                    <a href="#condiciones" data-toggle="tab">Condiciones</a>
                </li>
            </ul>
        </div>

    </div>
    
   
    
    
    <div class="panel-body">
        <div class="tab-content">
            
            
            
            
            
            <div class="tab-pane active" id="tarifas" >
                <div>

                    <table width="100%"  style="margin-top: -15px; margin-left: -15px;">
                        <tr>
                            <td colspan="2">
                                <P style="font-size:11px">
                                    <b style="color:#FF9900;">PAIS:</b> <?php echo $this->objProgramas[0]->getPais(); ?>, 
                                    <b style="color:#FF9900; margin-left: 10px;">CIUDAD:</b> <?php echo $this->objProgramas[0]->getCiudad(); ?> 
                                    <label style="margin-right: 30px;">&nbsp;</label>
                                    <?php if($this->objProgramas[0]->getAereo()) { ?><img src="<?php echo $_layoutParamsCB['ruta_img']; ?>ok.png" width="16" style="margin-left:5px;" > Aereo <?php } ?>
                                    <?php if($this->objProgramas[0]->getHotel()) { ?><img src="<?php echo $_layoutParamsCB['ruta_img']; ?>ok.png" width="16" style="margin-left:5px;"> Hotel <?php } ?>
                                    <?php if($this->objProgramas[0]->getTraslado()) { ?><img src="<?php echo $_layoutParamsCB['ruta_img']; ?>ok.png" width="16" style="margin-left:5px;" > Traslado <?php } ?>
                                </P>
                            </td>
                        </tr>
                        <tr>
                            <td width="210" valign="top">
                                <?php 
                                if($this->objProgramas[0]->getImagen()) { ?>
                                    <img src="<?php echo $_layoutParamsCB['ruta_programas'] . $this->objProgramas[0]->getImagen(); ?>" width="200" class="img-thumbnail" style="margin-right: 10px;">
                                <?php } else {
                                ?>
                                <img src="<?php echo $_layoutParamsCB['ruta_programas']; ?>sin_foto.png" width="150" class="img-thumbnail" style="margin-right: 10px;">
                                <?php } ?>
                            </td>
                            <td>
                                <b style="color:#FF9900;">INCLUYE:</b> <br>
                                <span style="color:#008ccc;">&bull;</span> <?php echo substr($this->objProgramas[0]->getIncluye(), 0, -43); ?>
                                
                                <?php if($this->_PDF) { ?>
                                    <a id="btnDP_itinerario" class="btn btn-info btn-sm" onclick="fadeIn('detallePopup'); $('#divPopupIn').css('overflow-y', 'hidden'); abrePopup('divPopupIn', '<?php echo BASE_URL; ?>programas/itinerario', 'tituloPopup', 'Itinerario', '<?php echo $this->objProgramas[0]->getCodigo(); ?>');" style="width: 88px; float: right;" >Itinerario</a>
                                <?php } ?>
                            </td>
                        </tr>
                    </table>

                </div>

            </div>
            
            
            
            
            
            
            <div class="tab-pane" id="descripcion">
                <table width="100%" style="margin-top: -15px; margin-left: -15px;">
                    <tr>
                        <td colspan="2">
                            <?php echo $this->objProgramas[0]->getDescrip(); ?>
                        </td>
                    </tr>
                </table>
            </div>
            
            
            
            
            
            
            <div class="tab-pane" id="condiciones">
                <table width="100%" style="margin-top: -15px; margin-left: -15px;">
                        <tr>
                            <td colspan="2">
                                <p><b style="color:#FF9900; font-size:11px">DESCRIPCI&Oacute;N:</b><br> 
                                    <?php echo $this->objProgramas[0]->getNota(); ?>
                                </p>
                            </td>
                        </tr>
                        <!-- <tr>
                            <td>
                                <p>
                                   <b style="color:#FF9900; font-size:11px">SERVICIOS HOTEL:</b><br>
                                </p>
                            </td>
                            <td>
                                <p>

                                    <b style="color:#FF9900; font-size:11px">SERVICIOS HABITACI&Oacute;N:</b><br> 

                                </p>
                            </td>
                        </tr> -->
                    </table>
            </div>
        </div>
    </div>
    
    
    
    
    
    
    
<?php
if($this->objOpcProgramas) {
    $cntDP = 1;
    foreach($this->objOpcProgramas as $objOpcProg) {
?>
    <br />
    <div class="panel-heading" style="margin-top: 20px;" >
        Opci&oacute;n <?php echo $cntDP; if($objOpcProg->getEstado() == 'AVAILABLE') { ?>
            <div class="blink" style="float: right;"><button class="btn btn-warning btn-sm" > &iexcl; DISPONIBLE ! </button><?php //echo $objOpcProg->getEstado(); ?></div>
        <?php } ?>
            <div style="float: right;"><a href="#" onclick="fadeIn('detallePopup'); $('#divPopupIn').css('overflow-y', 'scroll'); abrePopup('divPopupIn', '<?php echo BASE_URL; ?>bloqueos/notas', 'tituloPopup', 'Nota de Programa', '<?php echo $objOpcProg->getIdOpc(); ?>');" title='Nota opcion'><img src="<?php echo $_layoutParamsCB['ruta_img']; ?>nota.png" width="24" style="margin-left:5px;" ></a></div>
            
        <script type="text/javascript">
            $(function(){
                $( "#tooltip_hotel_<?php echo $objOpcProg->getClaveOpc(); ?>" ).poshytip({ className: "tip-darkgray", alignY : "bottom" });
            });
        </script>
    </div>
    <div class="panel-body">
        <div class="tab-content" style="display: block;" id="tab_content_1_<?php echo $cntDP; ?>">
            
            
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" style="font-size:12px; width: 100%; margin-top: 20px;" align='center'> <!-- class="table table-striped table-bordered" -->
                <thead>
                    <tr style="background-color:#34495e; color: #FFFFFF" role="row">
                        <th role="columnheader" style="padding-left: 2px;">Hotel</th>
                        <th role="columnheader" style="padding-left: 2px;">Direcci&oacute;n</th>
                        <th role="columnheader" style="padding-left: 2px;">Categoria</th>
                        <th role="columnheader" style="padding-left: 2px;">Tipo Habitaci&oacute;n</th>
                    </tr>
                </thead>
                
                <?php
                $DP_hoteles= $objOpcProg->getNombreHotel();
                $DP_cod_hoteles= $objOpcProg->getCodHotel();
                $DP_dirHot= $objOpcProg->getDir();
                $DP_catHot= $objOpcProg->getCat();
                $DP_thHot= $objOpcProg->getTipoHab();
                $DP_cntHoteles = count($objOpcProg->getNombreHotel());
                
                for($i = 0; $i < $DP_cntHoteles; $i++) {
                    $_tittle = false;
                    $_tittle = "<table align='center'  width='210px' style='background-color:#FFFFFF; border:2px solid #0085CC; vertical-align:top'>
                    <tr>
                        <td style='color:#FFFFFF; background-color:#0085CC' width='70px' align='center'>Fotos</td>
                        <td style='color:#FFFFFF; background-color:#0085CC' width='70px' align='center'>Mapa</td>
                        <td style='color:#FFFFFF; background-color:#0085CC' width='70px' align='center'>Servicios</td>
                    </tr>

                    <tr>	
                        <td align='center'>
                            <a data-toggle='modal' href='#myModal' 
                                onClick='fadeIn(&quot;detallePopup&quot;); $(&quot;#divPopupIn&quot;).css(&quot;overflow-y&quot;, &quot;scroll&quot;); abrePopup(&quot;divPopupIn&quot;, &quot;" . BASE_URL . "bloqueos/fotosHotel&quot;, &quot;tituloPopup&quot;, &quot;Fotos Hotel&quot;, $DP_cod_hoteles[$i]);' >
                            <img src='" . $_layoutParamsCB['ruta_img'] . "fotos.png' border='0' height='25' title='Fotos' />
                            </a>
                        </td>
                        <td align='center'>
                            <a data-toggle='modal' href='#myModal' 
                                onClick='fadeIn(&quot;detallePopup&quot;); $(&quot;#divPopupIn&quot;).css(&quot;overflow-y&quot;, &quot;scroll&quot;); abrePopup(&quot;divPopupIn&quot;, &quot;" . BASE_URL . "bloqueos/mapas&quot;, &quot;tituloPopup&quot;, &quot;Google Maps&quot;, $DP_cod_hoteles[$i]);' >
                                <img src='" . $_layoutParamsCB['ruta_img'] . "ubicacion.png' border='0' height='26px' title='Mapa' />
                            </a>
                        </td>
                        <td align='center'>
                            <a data-toggle='modal' href='#myModal' 
                                        onClick='fadeIn(&quot;detallePopup&quot;); $(&quot;#divPopupIn&quot;).css(&quot;overflow-y&quot;, &quot;scroll&quot;); abrePopup(&quot;divPopupIn&quot;, &quot;" . BASE_URL . "bloqueos/servicios&quot;, &quot;tituloPopup&quot;, &quot;Todos los servicios&quot;, $DP_cod_hoteles[$i]);'>
                                <img src='" . $_layoutParamsCB['ruta_img'] . "servicios.png' border='0' height='27' title='Servicios' />
                            </a>
                        </td>
                    </tr>

                    <tr>
                        <td style='color:#FFFFFF; background-color:#0085CC' colspan='3' align='center'>Detalles Hotel</td>
                    </tr>

                    <tr>
                        <td style='color:#000000;' colspan='3' align='left'>&nbsp;Categoria: <strong>$DP_catHot[$i]</strong></td>
                    </tr>                           
                    <tr>
                        <td style='color:#000000;' colspan='3' align='left'>
                            &nbsp;Tipo Habitaci&oacute;n:  <strong>$DP_thHot[$i]</strong>
                            <a data-toggle='modal' href='#myModal' 
                                        onClick='fadeIn(&quot;detallePopup&quot;); $(&quot;#divPopupIn&quot;).css(&quot;overflow-y&quot;, &quot;scroll&quot;); abrePopup(&quot;divPopupIn&quot;, &quot;" . BASE_URL . "bloqueos/fotosHotel&quot;, &quot;tituloPopup&quot;, &quot;Fotos Tipo Habitaci&oacute;n&quot;, 99999999999999);'>
                            <img src='".$_layoutParamsCB['ruta_img']."camara.png' align='bottom' border='0' width='16px' title='Fotos tipo habitaci&oacute;n' />
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td style='color:#000000;' colspan='3' align='left'>&nbsp;Plan Alimenticio: <strong>Plan</strong></td>
                    </tr>
                    <tr>
                        <td style='color:#000000;' colspan='3' align='left'>&nbsp;Ciudad Hotel: <strong>Ciudad</strong></td>
                    </tr>
                </table>";
                ?>
                    <tr>
                        <td style="color: #DF5F00; padding: 2px; vertical-align: middle;">
                            <a id="tooltip_hotel_<?php echo $objOpcProg->getClaveOpc(); ?>"  style="cursor:pointer" title="<?php echo $_tittle; ?>"><?php echo $DP_hoteles[$i]; ?></a>
                        </td>
                        <td style="width: 300px;"><?php echo $DP_dirHot[$i]; ?></td>
                        <td style="width: 80px;"><?php echo $DP_catHot[$i]; ?></td>
                        <td style="padding: 2px; vertical-align: middle; width: 100px;"><?php echo $DP_thHot[$i]; ?></td>
                    </tr>
                    <?php
                }?>
            </table>
            
            
            
            <!-- RESERVAR -->
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" align="center">
                <tr>
                    <td style="font-size: 12px; text-align: center"> SINGLE </td>
                    <td style="font-size: 12px; text-align: center"> DOBLE </td>
                    <td style="font-size: 12px; text-align: center"> TRIPLE </td>
                    <td style="font-size: 12px; text-align: center"> </td>
                </tr>

                <tr>
                    <td style="padding: 2px; vertical-align: middle;" align="center">
                        <label style="color: #DF5F00; font-weight: bold; font-size:20px;"><?php echo Functions::formatoValor($objOpcProg->getMoneda(), $objOpcProg->getVVenSGL()); ?></label><br>
                    </td>
                    <td style="padding: 2px; vertical-align: middle;" align="center">
                        <label style="color: #DF5F00; font-weight: bold; font-size:20px;"><?php echo Functions::formatoValor($objOpcProg->getMoneda(), $objOpcProg->getVVenDBL()); ?></label><br>
                    </td>
                    <td style="padding: 2px; vertical-align: middle;" align="center">
                        <label style="color: #DF5F00; font-weight: bold; font-size:20px;"><?php echo Functions::formatoValor($objOpcProg->getMoneda(), $objOpcProg->getVVenTPL()); ?></label><br>
                    </td>
                    <td style="padding: 2px; vertical-align: middle;" align="center">
                        <a id="btnDP_reservar_<?php echo $cntDP; ?>" class="btn btn-success btn-sm" style="width: 88px;" 
                           onclick="fadeIn('detallePopup'); $('#divPopupIn').css('overflow-y', 'scroll'); Programa.prototype.pasajerosProg('<?php echo $cntDP; ?>',  
                                       'divPopupIn', 
                                       '<?php echo BASE_URL; ?>programas/pasajeros', 
                                       '<?php echo $objOpcProg->getVVenSGL(); ?>',
                                       '<?php echo $objOpcProg->getVVenDBL(); ?>',
                                       '<?php echo $objOpcProg->getVVenTPL(); ?>',
                                       '<?php echo $objOpcProg->getMoneda(); ?>',
                                       '<?php echo $objOpcProg->getClaveOpc(); ?>'
                                       );"> RESERVAR 
                        </a>
                    </td>
                </tr>
            </table>
            <!-- END: RESERVAR -->
            
        </div>
        
    </div>
    
<?php $cntDP++; } } ?>
    
    
</div>






