<div id="imprimirSector">
    <head><title>Programa</title></head>
    <?php
    if (Session::get('sess_codigo_cliente_url') == '3f7a2611ee08c6645796463e0bb1ae7f') {
        echo '<img  src="' . $_layoutParamsCB['ruta_img'] . 'logo_tc.jpg" style="margin-top:-20px;" />';
    } else {
        echo '<img  src="' . $_layoutParamsCB['ruta_img'] . 'logo.jpg" style="margin-top:-20px;" />';
    }
    ?>
    <center><h4><b><?php echo $this->objProgramas[0]->getTitulo(); ?></b></h4></center>

    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <table>
                <tr>
                    <td><b>Fecha de Viaje</b>: &nbsp;</td>
                    <td><b><?php echo $this->ML_fechaIni_PRG; ?></b></td>
                </tr>
            </table>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <table class="tabla-hover" style="margin-bottom: 0px; font-size: 12px; border: 1px #34495e solid;width: 100%;">


                <thead style="background-color:#34495e; color: #FFFFFF;">
                <th style=" padding: 2px; text-align: center; width: 250px;">Hotel</th>
                <th style=" padding: 2px; width: 80px; text-align: center;">Categoria</th>
                <th style=" padding: 2px; width: 80px; text-align: center;">Habitaci&oacute;n</th>
                <th style=" padding: 2px; width: 90px; text-align: center;">P. Alimenticio</th>

                </thead>

                <tbody>
                    <?php
                    $i = 0;

                    foreach ($this->hot as $val) {
                        ?>
                        <tr align="center">
                            <td ><?php echo $val; ?></td>
                            <td >
                                <?php
                                if (strlen($this->cant[$i]) == 2) {
                                    for ($j = 1; $j <= 5; $j++) {
                                        if ($j <= substr($this->cant[$i], 0, 1)) {
                                            ?>
                                            <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>star_on.png" height='12' title='Categoria' />
                                        <?php } else { ?>
                                            <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>star_off.png" height='12' title='Categoria' />
                                            <?php
                                        }
                                    }
                                } else {
                                    echo $this->cant[$i];
                                }
                                ?>
                            </td>
                            <td ><?php echo $this->hab[$i]; ?></td>
                            <td ><?php echo $this->plan[$i]; ?></td>
                        </tr>
                        <?php
                        $i++;
                    }
                    ?>
                </tbody> 
            </table>
        </div>
    </div>
    <div class="row"style="margin-top: 10px; margin-bottom: 10px;">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" align="center">
                        <tr>
                            <td style="font-size: 12px; text-align: center"> SINGLE </td>
                            <td style="font-size: 12px; text-align: center"> DOBLE </td>
                            <td style="font-size: 12px; text-align: center"> TRIPLE </td>
                            <td style="font-size: 12px; text-align: center"> NI&Ntilde;O 1</td>
                            <td style="font-size: 12px; text-align: center"> NI&Ntilde;O 2 </td>
                            <td style="font-size: 12px; text-align: center"> PLAN FAMILIAR </td>
                        </tr>
                        <tr align="center">
                            <td style="padding: 2px; vertical-align: middle;" align="center">
                                <label style="color: #DF5F00; font-weight: bold; font-size:20px;<?php if($this->pago && $this->moneda ==='D'){?>margin-bottom: -1px;<?php } ?>"><?php if($this->sgl==0){ echo'--'; }else{ echo Functions::formatoValor($this->moneda, $this->sgl);} ?></label>
                                <br><?php if( $this->pago && $this->moneda ==='D' ){?>
                                <b style=" font-size: 13px; color : #34495e;"><?php echo Functions::formatoValor('P',$this->sgl * Session::get('sess_tcambio'));?></b><br>
                                <?php }?>
                            </td>
                            <td style="padding: 2px; vertical-align: middle;" align="center">
                                <label style="color: #DF5F00; font-weight: bold; font-size:20px;<?php if($this->pago && $this->moneda ==='D'){?>margin-bottom: -1px;<?php } ?>"><?php if($this->dbl==0){ echo '--'; }else{echo Functions::formatoValor($this->moneda, $this->dbl);} ?></label>
                                <br><?php if( $this->pago && $this->moneda ==='D' ){?>
                                <b style=" font-size: 13px; color : #34495e;"><?php echo Functions::formatoValor('P',$this->dbl * Session::get('sess_tcambio'));?></b><br>
                                <?php }?>
                            </td>
                            <td style="padding: 2px; vertical-align: middle;" align="center">
                                <label style="color: #DF5F00; font-weight: bold; font-size:20px;<?php if($this->pago && $this->moneda ==='D'){?>margin-bottom: -1px;<?php } ?>"><?php if($this->tpl==0){ echo '--'; }else{echo Functions::formatoValor($this->moneda, $this->tpl);} ?></label>
                                <br><?php if( $this->pago && $this->moneda ==='D' ){?>
                                <b style=" font-size: 13px; color : #34495e;"><?php echo Functions::formatoValor('P',$this->tpl * Session::get('sess_tcambio'));?></b><br>
                                <?php }?>
                            </td>

                            <td style="padding: 2px; vertical-align: middle;" align="center">
                                <label style="color: #DF5F00; font-weight: bold; font-size:20px; <?php if($this->pago && $this->moneda ==='D' && $this->chd1 > 0){?>margin-bottom: -1px;<?php } ?>"><?php if ($this->chd1 == 0) {
                               echo "--";
                           } else {
                               echo Functions::formatoValor($this->moneda, $this->chd1);
                           } ?></label><br>
                           <?php if($this->pago && $this->moneda ==='D' && $this->chd1 > 0 ){?>
                                <b style=" font-size: 13px; color : #34495e;"><?php if ($this->chd1 > 0) { echo Functions::formatoValor('P',$this->chd1 * Session::get('sess_tcambio')); } ?></b><br>
                                <?php } ?>
                            </td>
                            <td style="padding: 2px; vertical-align: middle;" align="center">
                                <label style="color: #DF5F00; font-weight: bold; font-size:20px; <?php if($this->pago && $this->moneda ==='D' && $this->chd2 > 0){?>margin-bottom: -1px;<?php } ?>"><?php if ($this->chd2 == 0) {
                               echo "--";
                           } else {
                               echo Functions::formatoValor($this->moneda, $this->chd2);
                           } ?></label><br>
                           <?php if($this->pago && $this->moneda ==='D' && $this->chd2 > 0 ){?>
                                <b style=" font-size: 13px; color : #34495e;"><?php if ($this->chd2 > 0) { echo Functions::formatoValor('P',$this->chd2 * Session::get('sess_tcambio')); } ?></b><br>
                                <?php } ?>
                            </td>
                            <td style="padding: 2px; vertical-align: middle;" align="center">
                                <label style="color: #DF5F00; font-weight: bold; font-size:20px; <?php if($this->pago && $this->moneda ==='D' && $this->pf > 0){?>margin-bottom: -1px;<?php } ?>"><?php if ($this->pf == 0) {
                               echo "--";
                           } else {
                               echo Functions::formatoValor($this->moneda, $this->pf);
                           } ?></label><br>
                           <?php if($this->pago && $this->moneda ==='D' && $this->pf > 0 ){?>
                                <b style=" font-size: 13px; color : #34495e;"><?php if ($this->pf > 0) { echo Functions::formatoValor('P',$this->pf * Session::get('sess_tcambio')); } ?></b><br>
                                <?php } ?>
                            </td>
                        </tr>
        </table>
    </div>
    </div>
    <div class="row" style="margin-top: 10px; margin-bottom: 10px;">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <div class="panel-body" style="border-top:1px solid #d2d3d6;">
                <table style="font-size:12px;">
                    <tr>
                        <td colspan="7" class="text-left">
                            <h5 style="color:#0085cc"><b>INCLUYE</b></h5>
                            <img  src="<?php echo $_layoutParamsCB['ruta_img']; ?>tick.png" width="12px" />
                            <?php echo substr(str_replace("<span style='color:#008ccc;'>&bull;</span>", '<img src="' . $_layoutParamsCB['ruta_img'] . 'tick.png" width="12px" />', $this->objProgramas[0]->getIncluye()), 0, -95); ?>
                        </td>

                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <table  style="font-size:12px;">
                <tr>
                    <td>
                        <b>Notas</b>:
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php echo $this->nota[0]->getNota();?>
                    </td>
                </tr> 
            </table> 
        </div>
    </div>
    <center>
        <div style="width:90%; text-align:right;" >
            <img class="oculto" src="<?php echo $_layoutParamsCB['ruta_img']; ?>print.png" onClick="javascript:imprSelec('imprimirSector')" width="32" style="cursor:pointer;" /> &nbsp;<br />&nbsp;
        </div>
    </center>
</div>
<script language="Javascript">
    function imprSelec(nombre)
    {
        var ficha = document.getElementById(nombre);
        var ventimp = window.open(' ', 'popimpr');
        ventimp.document.write(ficha.innerHTML);
        ventimp.document.close();
        ventimp.print( );
        ventimp.close();
    }
</script>   