<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <body>
        <table border="0" cellpadding="3" cellspacing="0" style="font-family:Verdana, Arial, Helvetica, sans-serif; font-size:11px;">
            <tr>
                <td colspan="3"><img src ="{logo}" ></td>
            </tr>
            <tr>
                <td colspan="4" height="30px" align="right">{ciudad} {fecha} <br> hora: {hora}</td>
            </tr>
            
            <tr>
                <td><strong>TO</strong></td>
                <td><strong style="font-size:15px;">:</strong></td>
                <td>{to}</td>
            </tr>
            <tr>
                <td><strong>Direccion</strong></td>
                <td><strong style="font-size:15px;">:</strong></td>
                <td>{toDirec} - {todCiudad}</td>
            </tr>
            <tr>
                <td><strong>FROM</strong></td>
                <td><strong style="font-size:15px;">:</strong></td>
                <td>Oris Web </td>
            </tr>
            <tr>
                <td colspan="3" height="25px">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="3">Solicitud: <u><strong>{solicitud}</strong></u></td>
            </tr>

            <tr>
                <td colspan="3">Nombre Pax: <strong>{pasajero}</strong> / File: <strong>{file}</strong></td>
            </tr>

            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>

            {glosa}            
            <tr>
                <td colspan="3" style="border-bottom:thin; border-bottom-color:#000000"> ________________________________________________________________________________ </td>
                <td width="40px" style="border-bottom:thin; border-bottom-color:#000000">&nbsp;</td>
            </tr>

            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="3">
                    Atte. <br /> 
                    <strong>Oris Web</strong> <br />
                    {correoProveedor} <br />
                    Fono: {fonoProveedor}<br />
                    {nombreProveedor}<br />
                </td>
            </tr>
            <!--if(trim($dest) == ""){
            <tr>
                <td colspan="3" align="center" style="font-size:15;color:#FF0000;">
                    <strong>**Atención**<br />Proveedor no tiene Correo Electronico Ingresado</strong>
                </td>
            </tr>
            }-->
        </table>
    </body>
</html>