<html>
    <head></head>
    <body>
        <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">	  
            <tr>
                <td align="left">
                    <?php
                    if (Session::get('sess_codigo_cliente_url') == '3f7a2611ee08c6645796463e0bb1ae7f') {
                        echo '<img  src="' . $_layoutParamsCB['ruta_img'] . 'logo_tc.jpg" style="margin-top:-20px;" />';
                    } else {
                        echo '<img  src="' . $_layoutParamsCB['ruta_img'] . 'logo.jpg" style="margin-top:-20px;" />';
                    }
                    ?>
                </td>
                <td width="50%" align="right" class="TopBot">
                    Tel&eacute;fonos : <?php echo ENT_FONO; ?><br />	      
                    <a href="<?php echo ENT_WEB; ?>" target="_blank"> <?php echo ENT_WEB; ?> <br /></a>
                </td>


            </tr>	
        </table>
        <table width="100%" border="0" align="center" cellpadding="2" cellspacing="2" class="Base">
            <tr>
                <td height="60" colspan="3" align="center"><h3><b>Solicitud de Cotizaci&oacute;n</b></h3></td>
            </tr>	  
            <?php if (!Session::get('sess_boton_pago')) { ?>
                <tr>
                    <td width="18%"><strong>Agencia</strong></td>
                    <td width="2%">:</td>
                    <td width="80%"><?php echo Session::get('sess_agencia'); ?></td>
                </tr>

                <tr>
                    <td width="18%"><strong>Usuario</strong></td>
                    <td width="2%">:</td>
                    <td width="80%"><?php echo Session::get('sess_nombre'); ?></td>
                </tr>
            <?php } ?>
            <tr>
                <td width="18%"><strong>Nombre pasajero</strong></td>
                <td width="2%">:</td>
                <td width="80%"><?php echo $this->nom; ?></td>
            </tr>

            <tr>
                <td width="18%"><strong>Tel&eacute;fono</strong></td>
                <td width="2%">:</td>
                <td width="80%"><?php echo $this->tele; ?></td>
            </tr>

            <tr>
                <td><strong>Correo </strong></td>
                <td>:</td>
                <td><?php echo $this->correo; ?></td>	  
            </tr>
        </table>
        <br />
        <table width="100%" border="0" align="center" cellpadding="2" cellspacing="2" class="Base">
            <tr>
                <td width="18%"><strong>Programa</strong></td>
                <td width="2%">:</td>
                <td width="80%"><?php echo Session::get('sess_claveOpc') . '&nbsp;&nbsp;-&nbsp;&nbsp;' . Session::get('sess_nombrePrograma'); ?></td>
            </tr>

            <tr>
                <td width="18%"><strong>ciudad</strong></td>
                <td width="2%">:</td>
                <td width="80%"><?php echo Session::get('sess_ciudadPrograma'); ?></td>
            </tr>

            <tr>
                <td><strong>fecha de Salida</strong></td>
                <td>:</td>
                <td><?php echo $this->ML_fechaIni_PRG; ?></td>	  
            </tr>
        </table>
        <div style="width:100%;">
            <center><h4><b>Alternativa de Hoteles seleccionados</b></h4></center>
            <table cellpadding="0" cellspacing="0" border="0" class=" table-striped table-bordered" style="font-size:12px; width: 80%; margin-top: 20px;">
                <thead>
                    <tr style="background-color:#34495e; height: 3px; color: #FFFFFF" role="row">
                        <th role="columnheader" style="padding-left: 2px; height: 3px;text-align: center;">Hotel</th>
                        <th role="columnheader" style="padding-left: 2px; height: 3px;text-align: center;">Categoria</th>
                        <th role="columnheader" style="padding-left: 2px; height: 3px;text-align: center;">Tipo Habitaci&oacute;n</th>
                        <th role="columnheader" style="padding-left: 2px; height: 3px;text-align: center;">Plan Alimenticio</th>
                    </tr>
                </thead>
                <?php
                $i = 0;
                foreach ($this->hot as $val) {
                    ?>
                    <tr>
                        <td style="height: 22px; width:300px;"><?php echo $val; ?></td>
                        <td style="height: 22px;">
                            <?php
                            if (strlen($this->cant[$i]) == 2) {
                                for ($j = 1; $j <= 5; $j++) {
                                    if ($j <= substr($this->cant[$i], 0, 1)) {
                                        ?>
                                        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>star_on.png" height='12' title='Categoria' />
                                    <?php } else { ?>
                                        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>star_off.png" height='12' title='Categoria' />
                                        <?php
                                    }
                                }
                            } else {
                                echo $this->cant[$i];
                            }
                            ?>
                        </td>
                        <td style="height: 22px;"><?php echo $this->hab[$i]; ?></td>
                        <td style="height: 22px;"><?php echo $this->plan[$i]; ?></td>
                    </tr>
                    <?php
                    $i++;
                }
                ?>
            </table>
        </div>
        <br />
        
        <div style="width:100%; ">
            <h4><b>Habitaciones</b></h4>

                <?php for ($i = 1; $i <= $this->cantHab; $i++) { ?>

                    <h4>Habitaci&oacute;n  <?php echo $i; ?></h4>
                    <table width="100%" border="0" align="center" cellpadding="2" cellspacing="2" class="Base">               
                        <tr style="text-align:left;" >
                            <td width="7%">Adultos</td>
                            <td width="2%">:</td>
                            <td width="93%"><?php echo Session::get('adult_' . $i); ?></td>

                            <?php if (Session::get('child_' . $i) > 0) { ?>
                                <td width="7%">Child</td>
                                <td width="2%">:</td>
                                <td width="93%"><?php echo Session::get('child_' . $i); ?></td>
                            <?php } ?>
                        </tr>
                        <tr>
                            <?php if (Session::get('child_' . $i) > 0) { ?>
                                <td width="7%">Edad C1</td>
                                <td width="2%">:</td>
                                <td width="93%"><?php echo Session::get('EdadChild_1_' . $i); ?></td>
                                <td width="7%">Edad C2</td>
                                <td width="2%">:</td>
                                <td width="93%"><?php echo Session::get('EdadChild_1_' . $i); ?></td>
                            <?php } ?>
                        </tr>
                    </table>

                <?php } ?>

            
        </div>
        <div class="row">
            <div class="col-md-12">
                <table>
                    <tr>
                        <td><b>Nota :</b></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->nota; ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </body>
</html>