<form class="frmDetalleReserva_1_<?php echo $this->cntP; ?>">
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" style="width:50%" align="center">
        <tr>
            <td><span style="padding-left:10px;">Habitaci&oacute;n:</span></td>
            <td>
                <select name="DP_cmbHab" id="DP_cmbHab" class="form-control" onchange="habitaciones('<?php echo $this->cntP; ?>_DP_tblHab_B', this.value)">
                    <option value="0">Seleccione</option>
                    <?php for($i=1; $i<=3; $i++) { ?>
                        <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>

        <tr>
            <td colspan="2">

            <?php for($i=1; $i<=3; $i++) { ?>
                <div id="<?php echo $this->cntP; ?>_DP_tblHab_B_<?php echo $i; ?>" style="display:none;">
                    <table width="100%" border="0" cellspacing="0" cellpadding="5">
                        <tr>
                            <td>Adultos</td>
                            <td>
                                <select name="DP_cmbAdultos_<?php echo $i; ?>" id="DP_cmbAdultos_<?php echo $i; ?>">
                                <?php for($x=1; $x<=3; $x++) { ?>
                                    <option value="<?php echo $x; ?>"><?php echo $x; ?></option>
                                <?php } ?>
                                </select>
                            </td>
                            <td>Child</td>
                            <td>
                                <select name="DP_cmbChild_<?php echo $i; ?>" id="DP_cmbChild_<?php echo $i; ?>" >
                                <?php for($x=0; $x<=2; $x++) {?>                          
                                    <option value="<?php echo $x; ?>"><?php echo $x; ?></option>
                                <?php } ?>
                                </select>
                            </td>
                        </tr>


                        <!-- <tr>
                            <td>Infant</td>
                            <td colspan="3">
                                <select name="DP_inf_<?php echo $i; ?>" id="DP_inf_<?php echo $i; ?>">
                                <?php for($x=0; $x<=1; $x++) { ?>                          
                                    <option value="<?php echo $x; ?>"><?php echo $x; ?></option>
                                <?php } ?>
                                </select>
                            </td>                    	  
                        </tr> -->

                    </table>
                    <hr />
                </div>      
            <?php } ?>




            </td>
        </tr>


        <tr>
            <td colspan="2" align="right">
                <a class="btn btn-primary btn-sm" id="Siguiente" onclick="fadeIn('detallePopup'); Programa.prototype.procesoDetallePasajeros('frmDetalleReserva_1_<?php echo $this->cntP; ?>', '<?php echo BASE_URL; ?>programas/detallePasajeros', 'Siguiente', 'divPopupIn');"> Siguiente </a>
            </td>
        </tr>
    </table>
</form>