<script type="text/javascript" src="http://www.google.com/jsapi?key=AIzaSyByJ-PrjAq7ZDCa8_bCGYB-hzoAJcInrug"></script>
<!-- MAPS -->
<script type="text/javascript">
    //<![CDATA[  
    google.load('maps', '2');
	var map;	
    function tercero(lat, lon, hotel){	
    if (GBrowserIsCompatible()) { 
        function createMarker(point,html) {
        var marker = new GMarker(point);
        GEvent.addListener(marker, "click", function() {
          marker.openInfoWindowHtml(html);});
        return marker;}			
      var map = new GMap2(document.getElementById("map3"));
      map.addControl(new GLargeMapControl());
      map.addControl(new GMapTypeControl());	  
      map.setCenter(new GLatLng(lat,lon),14);}	  
      var point = new GLatLng(lat,lon);
	  /*var marker = createMarker(point,'<div style="width:240px">El Capitolio de la Habana <a href="http://www.sitio.com">Pagina web<\/a> con mas información<\/div>');*/
	  var marker = createMarker(point,'<div style="width:240px">' + hotel + '<\/div>');
	  
      map.addOverlay(marker);
      
	  /*var point = new GLatLng(23.1368,-82.3816);
      var marker = createMarker(point,'La Universidad de la Habana')
      map.addOverlay(marker); */
	  }
    //]]>
</script>

<!-- Tooltip Detalle Hotel -->
<link rel="stylesheet" href="<?php echo $_layoutParams['ruta_css']; ?>tip-darkgray/tip-darkgray.css" type="text/css" />
<!-- End: Tooltip Detalle Hotel -->

<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">
            <ol class="breadcrumb">
                <li><a href="<?php echo BASE_URL . 'system'; ?>">Inicio</a></li>
                <li class="active">Busqueda de bloqueos</li>
            </ol>
            <h1>BLOQUEOS</h1>

        </div>
        <div class="container">
            
            <div class="row">
                <div class="col-md-12">
                
                    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" id="btnCerrar1PRG" data-dismiss="modal" aria-hidden="true" style="display:block">&times;</button>
                                    <h4 class="modal-title" id="tituloFormPRG"></h4>
                                </div>
                                
                                <div class="modal-body" id="divPopupPRG"></div>
                                
                                <div class="modal-footer">
                                    <center>
                                        <a class="btn btn-primary"n href="<?php echo BASE_URL; ?>system/programas" id="btnAceptarPRG" style="display:none">Volver a reservar</a>
                                    </center>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div>
                    
                    
                    
                    <div class="modal fade" id="myModalFotos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" id="btnCerrar1PRG" data-dismiss="modal" aria-hidden="true" style="display:block">&times;</button>
                                    <h4 class="modal-title" id="tituloFormFotos"></h4>
                                </div>
                                
                                <div class="modal-body" id="divPopupFotos"></div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div>
                
                
                    <div class="panel-group panel-info" id="accordion">
                       <?php
                                    $cntPopup=1;
                                    //$P_var_getProgramas= false;//$privateFunctions->exeSQL_SP($P_sql);
                                    //echo var_dump($this->objProgramas);
                                    if($this->objProgramas)
                                    { 
                                        $P_programaCompleto='';
                                        $P_programaHeader='';
                                        $P_programaDetalle='';
                                        $P_programaFooter='';
                                        $collapse=0;
                                        $P_cntProgramas=0;

                                        //foreach($this->objProgramas as $columPRG)
                                        foreach($this->objProgramas as $objProg)
                                        {
                                            ++$collapse;

                                            $P_error= $objProg->getERROR();
                                            if(!empty($P_error))
                                            {
                                                $P_Linea= $objProg->getLINEA();
                                                $P_Mensaje= $objProg->getMSJ();

                                                echo "Error: ".$P_error."<br />";
                                                echo "Linea: ".$P_Linea."<br />";
                                                echo "Mensaje: ".$P_Mensaje."<br />";
                                            }
                                            else
                                            {
                                                $P_idPRG= $objProg->getId();
                                                $P_nombrePRG= $objProg->getNombre();



                                                if(!empty($P_nombrePRG))
                                                {	//PROGRAMAS 
                                                        ++$P_cntProgramas;
                                                        if(!empty($P_programaCompleto))
                                                        {
                                                                $P_programaCompleto.=$P_programaDetalle;
                                                                $P_programaCompleto.=$P_programaFooter;

                                                                echo $P_programaCompleto;

                                                                $P_programaCompleto='';
                                                                $P_programaHeader='';
                                                                $P_programaDetalle='';
                                                                $P_programaFooter='';
                                                        }


                                                        $P_notaPRG=$objProg->getNota();


                                                        $P_programaHeader='
                                                        <form class="frmOpcionesPRG_'.$P_cntProgramas.'">
                                                         <div class="panel panel-default">
                                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse'.$P_cntProgramas.'">
                    <div class="panel-heading"><h4>'.$P_nombrePRG.'</h4></div>
                </a>
                <div id="collapse'.$P_cntProgramas.'" class="panel-collapse collapse">
                    <div class="panel-body">

                                                                <div class="col-md-6" style="width:100%;">
                                        <div class="panel panel-grape">
                                                <div class="panel-heading">
                                                        <h4> Salida: {fechaSalida} </h4>
                                                        <div class="options">
                                                                <i>{notaPRG} {itinerarioVuelo}</i>
                                                        </div>
                                                </div>
                                                <input type="hidden" id="P_idProg" name="P_idProg" value="'.$P_idPRG.'">
                                                <div class="panel-body">
                                                        <div class="table-responsive">
                                                                <table class="table table-hover" style="margin-bottom: 0px;">
                                                                        <tbody class="selects">';


                                                        $P_programaFooter='
                                                                        </tbody>
                                                                <tfoot>
                                                                    <tr>
                                                                        <td colspan="5" class="text-left">
                                                                            <h4 style="color:#0085cc"><b>INCLUYE</b></h4>';

                                                                            $P_var_getIncluye= $objProg->getIncluye();
                                                                            //echo $P_cntProgramas.' - '.var_dump($P_var_getIncluye);
                                                                            //echo var_dump($P_var_getIncluye[0][0]);
                                                                            //echo $P_var_getIncluye[0][0]->getCodigo();
                                                                            //echo $P_var_getIncluye[0][0]->getNombre();
                                                                            //echo count($P_var_getIncluye[0]);
                                                                            if($P_var_getIncluye)
                                                                            {
                                                                                $xx=0;
                                                                                $hh=0;
                                                                                $P_ciudadHotel=NULL;
                                                                                for($i=0; $i<=5; $i++){$P_arrayCiudadHotel[$i]=NULL;}
                                                                                //foreach($P_var_getIncluye as $columInclu)
                                                                                for($i=0; $i<count($P_var_getIncluye[0]); $i++)
                                                                                {
                                                                                    if($P_var_getIncluye[0][$i]->getCodigo()!='CGO' && $P_var_getIncluye[0][$i]->getNombre()!='')
                                                                                    {
                                                                                        if($P_var_getIncluye[0][$i]->getCiudad()!='')
                                                                                        {
                                                                                            $P_arrayCiudadHotel[$xx]= $P_var_getIncluye[0][$i]->getCiudad();
                                                                                            $xx++;
                                                                                        }

                                                                                        if($P_var_getIncluye[0][$i]->getCodigo()=='HTL')
                                                                                        {
                                                                                            $P_ciudadHotel= " / ".$P_arrayCiudadHotel[$hh];
                                                                                            $hh++;
                                                                                        }
                                                                                        else
                                                                                        {
                                                                                            $P_ciudadHotel=NULL;
                                                                                        }

                                                                                        if($P_var_getIncluye[0][$i]->getNoches()<10 && $P_var_getIncluye[0][$i]->getNoches()>0)
                                                                                        {
                                                                                            $P_varNoches="0".$P_var_getIncluye[0][$i]->getNoches()." Noches ";
                                                                                        }
                                                                                        else if($P_var_getIncluye[0][$i]->getNoches()>=10)
                                                                                        {
                                                                                            $P_varNoches=$P_var_getIncluye[0][$i]->getNoches()." Noches ";
                                                                                        }
                                                                                        else
                                                                                        {
                                                                                            $P_varNoches="";
                                                                                        }
                                                                                        
                                                                                        $P_programaFooter.='<img  src="'.$_layoutParams['ruta_img'].'tick.png" width="12px" /> '.$P_varNoches.$P_var_getIncluye[0][$i]->getNombre().$P_ciudadHotel."<br>";
                                                                                            
                                                                                    }
                                                                                }
                                                                            }



                                                        $P_programaFooter.='</td>
                                                                        </tr>

                                                                        <tr>
                                                                                <td colspan="5" align="center">
                                                                                        <a data-toggle="modal" href="#myModal" 
                                                                                        onClick="validaReserva(\'frmOpcionesPRG_'.$P_cntProgramas.'\', \'' . BASE_URL . 'bloqueos/reservaPrograma\', \'divPopupPRG\', \'tituloFormPRG\', \'Formulario de reserva\');"
                                                                                        class="btn btn-primary">Comenzar reserva</a>
                                                                                </td>
                                                                        </tr>
                                                                </tfoot>
                                                        </table>
                                                </div>
                                        </div>
                                </div>
                        </div>
                                                        </div></div> </div> <div class="panel panel-default"></div> </form> ';


                                                        $P_programaCompleto.=$P_programaHeader;
                                                }
                                                else
                                                {	//OPCIONES 

                                                        $P_idOpc= $objProg->getIdOpc();
                                                        $P_fechaDesde= $objProg->getDesde();
                                                        $P_fechaSalida= Functions::invertirFecha($P_fechaDesde, "/", "/");
                                                        
                                                        $vHabTMP= $objProg->getValorHab();
                                                        $P_vHab_1_Row= $vHabTMP[0];
                                                        $P_vHab_2_Row= $vHabTMP[1];
                                                        $P_vHab_3_Row= $vHabTMP[2];

                                                        $P_notaOPC= $objProg->getNotaOpc();

                                                        $P_monedaSP= $objProg->getMoneda();
                                                        $P_monedaSPView= Functions::getTipoMoneda($P_monedaSP);

                                                        $P_valorOpcion= ($P_vHab_1_Row+$P_vHab_2_Row+$P_vHab_3_Row);
                                                        $P_valorOpcionView= Functions::formatoValor($P_monedaSP, $P_valorOpcion);




                                                        $P_itinerarioVuelo='';
                                                        if($objProg->getItiVuelo())
                                                        {
                                                            $P_itinerarioVueloView='<a data-toggle="modal" href="#myModal" 
                                                                onClick="abrePopup(\'divPopupPRG\', \'' . BASE_URL . 'system/itinerarioVuelo\', \'tituloFormPRG\', \'Itinerario vuelo\', \''.$P_idOpc.'\');">
                                                                <img src="'.$_layoutParams['ruta_img'].'avion.png" width="24px" alt="Itinerario de Vuelos" title="Itinerario de Vuelos" />
                                                                </a>';
                                                        }
                                                        else
                                                        {
                                                            $P_itinerarioVueloView='';
                                                        }




                                                        if(!empty($P_notaPRG))
                                                        {
                                                            $P_notaPrgView='<a data-toggle="modal" href="#myModal" 
                                                                    onClick="abrePopup(\'divPopupPRG\', \'' . BASE_URL . 'bloqueos/condicionesGenerales\', \'tituloFormPRG\', \'Condiciones generales\', \''.$P_idPRG.'\');">
                                                                    <img src="'.$_layoutParams['ruta_img'].'nota.png" width="24px" alt="Condiciones generales" title="Condiciones generales" />
                                                                    </a>';

                                                        }
                                                        else
                                                        {
                                                            $P_notaPrgView='';
                                                        }



                                                        for($i=0; $i<5; $i++)
                                                        {
                                                            $P_arrayHotelesOpcion_H[$i]=NULL;
                                                            $P_arrayHotelesOpcion_CodH[$i]=NULL;

                                                            $P_arrayHotelesOpcion_PA[$i]=NULL;

                                                            $P_arrayHotelesOpcion_codTH[$i]=NULL;
                                                            $P_arrayHotelesOpcion_TH[$i]=NULL;

                                                            $P_arrayHotelesOpcion_cat[$i]=NULL;
                                                            $P_arrayHotelesOpcion_CIU[$i]=NULL;
                                                        }

                                                        $hotelesTMP= $objProg->getHoteles();
                                                        $codHotelesTMP= $objProg->getCodHoteles();
                                                        $paTMP= $objProg->getPA();
                                                        $thTMP= $objProg->getTH();
                                                        $codThTMP= $objProg->getCodTH();
                                                        $catTMP= $objProg->getCat();
                                                        $ciudadTMP= $objProg->getCiudad();
                                                        
                                                        $P_cntHoteles=0;
                                                        for($i=0; $i<5; $i++)
                                                        {
                                                            
                                                            $P_arrayHotelesOpcion_CodH[$i]= $codHotelesTMP[$i];//trim($columPRG["codHotel_".($i+1)]);

                                                            $P_arrayHotelesOpcion_PA[$i]= $paTMP[$i]; //trim($columPRG["PlanAlimenticio_".($i+1)]);
                                                            $P_arrayHotelesOpcion_codTH[$i]= $codThTMP[$i]; //trim($columPRG["codTipoHabitacion_".($i+1)]);
                                                            $P_arrayHotelesOpcion_TH[$i]= $thTMP[$i]; //trim($columPRG["TipoHabitacion_".($i+1)]);

                                                            $P_arrayHotelesOpcion_cat[$i]= $catTMP[$i]; //trim($columPRG["cat_".($i+1)]);
                                                            $P_arrayHotelesOpcion_CIU[$i]= $ciudadTMP[$i];//trim($columPRG["ciudad_".($i+1)]);

                                                            $P_arrayHotelesOpcion_H[$i]= $hotelesTMP[$i];//trim($columPRG["hotel_".($i+1)]);
                                                            if($hotelesTMP[$i]!='')
                                                            {
                                                                ++$P_cntHoteles;
                                                            }
                                                        }

                                                        //$P_programaDetalle.='DETALLE <br>';
                                                        $P_programaCompleto= str_replace('{fechaSalida}', $P_fechaSalida, $P_programaCompleto);
                                                        $P_programaCompleto= str_replace('{itinerarioVuelo}', $P_itinerarioVueloView, $P_programaCompleto);
                                                        $P_programaCompleto= str_replace('{notaPRG}', $P_notaPrgView, $P_programaCompleto);



                                                        $P_programaDetalle.='
                <tr>
                    <td width="20px">
                                                                <input type="radio" name="P_rdbOpcion_'.$P_cntProgramas.'" value="'.$P_idOpc.'">
                                                                ';


                                                                $P_programaDetalle.='<script type="text/javascript">
                                                                                                                        $(function(){
                                                                                                $("#div_opc_hotelProg_'.$cntPopup.'").poshytip({ className: "tip-darkgray", alignY : "bottom" });
                                                                                                                        });
                                                                                                                </script></td>';

                                                                for($i=0; $i<$P_cntHoteles; $i++)
                                                                {
                                                                    $_title=false;
                                                                    $_title="<table align='center'  width='210px' style='background-color:#FFFFFF; border:2px solid #0085CC; vertical-align:top'>
                                                                                                                        <tr>
                                                                                                                                <td style='color:#FFFFFF; background-color:#0085CC' width='70px' align='center'>Fotos</td>
                                                                                                                                <td style='color:#FFFFFF; background-color:#0085CC' width='70px' align='center'>Mapa</td>
                                                                                                                                <td style='color:#FFFFFF; background-color:#0085CC' width='70px' align='center'>Servicios</td>
                                                                                                                        </tr>

                                                                                                                        <tr>	
                                                                                                                                <td align='center'>
                                                    <a data-toggle='modal' href='#myModal' 
                                                                        onClick='abrePopup(&quot;divPopupPRG&quot;, 
                                                                                            &quot;" . BASE_URL . "system/fotosHotel&quot;, 
                                                                                            &quot;tituloFormPRG&quot;, 
                                                                                            &quot;Fotos Hotel&quot;, 
                                                                                            $P_arrayHotelesOpcion_CodH[$i]
                                                                                            );' >
                                                        <img src='".$_layoutParams['ruta_img']."fotos.png' border='0' height='25' title='Fotos' />
                                                    </a>
                                                    </td>
                                                                                                                                <td align='center'>
                                                    <a data-toggle='modal' href='#myModal' 
                                                                        onClick='abrePopup(&quot;divPopupPRG&quot;, &quot;" . BASE_URL . "system/mapas&quot;, &quot;tituloFormPRG&quot;, &quot;Google Maps&quot;, $P_arrayHotelesOpcion_CodH[$i]);' >
                                                        <img src='".$_layoutParams['ruta_img']."ubicacion.png' border='0' height='26px' title='Mapa' />
                                                    </a>
                                                    </td>
                                                                                                                                <td align='center'>
                                                    <a data-toggle='modal' href='#myModal' 
                                                                        onClick='abrePopup(&quot;divPopupPRG&quot;, &quot;" . BASE_URL . "system/servicios&quot;, &quot;tituloFormPRG&quot;, &quot;Todos los servicios&quot;, $P_arrayHotelesOpcion_CodH[$i]);'>
                                                    <img src='".$_layoutParams['ruta_img']."servicios.png' border='0' height='27' title='Servicios' />
                                                    </a>
                                                    </td>
                                                                                                                        </tr>

                                                                                                                        <tr>
                                                                                                                                <td style='color:#FFFFFF; background-color:#0085CC' colspan='3' align='center'>Detalles Hotel</td>
                                                                                                                        </tr>

                                                                                                                        <tr>
                                                                                                                                <td style='color:#000000;' colspan='3' align='left'>
                                                        &nbsp;Categoria: <strong>$P_arrayHotelesOpcion_cat[$i]</strong>
                                                    </td>
                                                                                                                        </tr>                           
                                                                                                                        <tr>
                                                                                                                                <td style='color:#000000;' colspan='3' align='left'>

                                                        &nbsp;Tipo Habitaci&oacute;n:  <strong>$P_arrayHotelesOpcion_TH[$i]</strong>
                                                        <a data-toggle='modal' href='#myModal' 
                                                                        onClick='abrePopup(&quot;divPopupPRG&quot;, &quot;" . BASE_URL . "system/fotosHotel&quot;, &quot;tituloFormPRG&quot;, &quot;Fotos Tipo Habitaci&oacute;n&quot;, 99999999999999);'>
                                                            <img src='".$_layoutParams['ruta_img']."camara.png' align='bottom' border='0' width='16px' title='Fotos tipo habitaci&oacute;n' />
                                                        </a>

                                                    </td>
                                                                                                                        </tr>
                                                                                                                        <tr>
                                                                                                                                <td style='color:#000000;' colspan='3' align='left'>
                                                        &nbsp;Plan Alimenticio: <strong>$P_arrayHotelesOpcion_PA[$i]</strong>
                                                    </td>
                                                                                                                        </tr>
                                                                                                                        <tr>
                                                                                                                                <td style='color:#000000;' colspan='3' align='left'>
                                                        &nbsp;Ciudad Hotel: <strong>$P_arrayHotelesOpcion_CIU[$i]</strong>
                                                    </td>
                                                                                                                        </tr>
                                                                                                                </table>";


$P_programaDetalle.='<td><a id="div_opc_hotelProg_'.$cntPopup.'" style="cursor:pointer" title="'.$_title.'">'.$P_arrayHotelesOpcion_H[$i].'</a></td>';		

                                                                $cntPopup++;
                                                                }

                                                        $P_programaDetalle.='<td style="color:#F00;" width="105px">'.$P_monedaSPView.' '.$P_valorOpcionView.'</td>
                                                                <td width="24px">';

                                                                if(!empty($P_notaOPC))
                                                                {
                                                                        $P_programaDetalle.='<a data-toggle="modal" href="#myModal" 
                                                                        onClick="abrePopup(\'divPopupPRG\', \'' . BASE_URL . 'system/notas\', \'tituloFormPRG\', \'Nota de Programa\', \''.$P_idOpc.'\');">
                                                                        <img src="'.$_layoutParams['ruta_img'].'nota.png" width="24px" alt="Notas" title="Notas" />
                                                                        </a>';
                                                                }

                                                        $P_programaDetalle.='</td>
                </tr>';
                                                }
                                            }



                                            if($this->objProgramasCNT==$collapse)
                                            {

                                                $P_programaCompleto.=$P_programaDetalle;
                                                $P_programaCompleto.=$P_programaFooter;

                                                echo $P_programaCompleto;
                                            }

                                        //usleep(500000);	 
                                        }
                                    }
                                    else
                                    {
                                ?>
                            <div id="divAlertWarHot" class="alert alert-dismissable alert-warning" style="display:block;">
                                No se encontraron registros para esta busqueda.
                            </div>
                                <?php
                                } //$this->procesoTerminado=true; ?> 
						
                    </div>
                </div>
            </div>

        </div> <!-- container -->
    </div> <!--wrap -->
</div> <!-- page-content -->