<script type="text/javascript" src="http://www.google.com/jsapi?key=AIzaSyByJ-PrjAq7ZDCa8_bCGYB-hzoAJcInrug"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>

<style>
    .tabla-hover table>tbody>tr:hover{background: #FFF;}
    //.hover-td:hover{background-color:#f7f8fa;}

    .td-background1{background-color: #f7f8fa;}
    .td-background2{background-color: #ffffff;}

</style>

<input type="hidden" id="ValiFormLogin" value="<?php if (Session::get('sess_boton_pago') || Session::get('Autenticado')) { echo '1'; } else { echo '0'; } ?>">

<?php if(Session::get('sess_iframe')){$sty_tc=""; } else { $sty_tc="margin-top:55px;"; } ?>
<div id="page-content" style="<?php echo $sty_tc ?>">
    <div id='wrap'>
        <div id="page-heading">
            <ol class="breadcrumb">
                <li><a href="<?php if($this->form==''){ echo BASE_URL . 'system'; } ?>">Inicio</a></li>
                <li class="active">Busqueda de bloqueos</li>
            </ol>
            <h3 style="margin-left: 18px;">PROGRAMAS CON AEREO CONFIRMADO EN <b style="color:#FF9900;"><?php echo Session::get('sess_BP_ciudadDes'); ?></b></h3>

        </div>
        <div class="container">

            <div class="row">
                <div class="col-md-12">

                    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" id="btnCerrar1PRG" data-dismiss="modal" aria-hidden="true" style="display:block">&times;</button>
                                    <h4 class="modal-title" id="tituloFormPRG"></h4>
                                </div>

                                <div class="modal-body" id="divPopupPRG"></div>

                                <div class="modal-footer">
                                    <center>
                                        <a class="btn btn-primary"n href="<?php echo BASE_URL . Session::get('SESS_CONTROLLER') . '/index/' . $this->form; ?>" id="btnAceptarPRG" style="display:none">Volver a reservar</a>
                                    </center>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div>

                    <div class="modal-content" id="loginPopup" style="position: fixed; left: 485px; top:30%; bottom: 10%; right: 210px; z-index: 9999;width: 500px; height: 339px;display: none;">
                        <div class="modal-header">
                            <button type="button" class="close" id="btnCerrarLo" style="display:block" onclick="fadeOut('loginPopup');">&times;</button>
                            <h4 class="modal-title" id="tituloPopup">Login</h4>
                        </div>

                        <div class="modal-body" id="divLoginIn" style="max-height: 400px;  overflow-y: scroll;">

                        </div>

                    </div>


                    <div class="modal fade" id="myModalFotos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" id="btnCerrar1PRG" data-dismiss="modal" aria-hidden="true" style="display:block">&times;</button>
                                    <h4 class="modal-title" id="tituloFormFotos"></h4>
                                </div>

                                <div class="modal-body" id="divPopupFotos"></div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div>
                    <div class="modal-content" id="condicionesPopup" style="position: fixed; left: 200px; top:10%; bottom: 10%; right: 210px; z-index: 9999; display: none;">
                        <div class="modal-header">
                            <button type="button" class="close" id="btnCerrarCon" style="display:block" onclick="fadeOut('condicionesPopup');
                                    fadeOut('detallePopup');">&times;</button>
                            <h4 class="modal-title" id="tituloPopup">Condiciones</h4>
                        </div>

                        <div class="modal-body" id="divPopupCon" style="max-height: 500px;  overflow-y: scroll;">


                        </div>
                        <!--<div class="modal-footer">
                            <center>
                                <table >
                                    <tr>
                                        <td style="width: 20px;"><input type="checkbox" id="checkCondiciones"></td>
                                        <td>He leido y acepto las condiciones</td>
                                                                          
                                    </tr>
                                </table>
                                <br>
                                <!--<table style="height: 30px; width: 219px;">
                                    <tr>
                                    <td><input type="button" class="btn btn-primary " id="aceptarCondiciones" onclick="Bloqueo.prototype.aceptarCondiciones();"value="Aceptar"></td>
                                        <td><input type="button"class="btn btn-primary  pull-right"onclick="fadeOut('condicionesPopup');fadeOut('detallePopup');$('#rP_btnProcesaRserva').prop('disabled',false);" value="Cancelar"></td>
                                    </tr>
                                </table>
                            </center>
                        </div>-->
                    </div>

                    <div class="panel-group panel-info" id="accordion">
                        <?php
                        $cnt = 0;
                        if ($this->objBloqueos) {
                            foreach ($this->objBloqueos as $objProg) {
                                $cnt++;
                                $OP_tipoHabi = $objProg->getTipoHab();
                                ?>


                                

        <!-- <form class="frmOpcionesPRG_<?php echo $cnt; ?>"> -->
                                <div class="panel panel-default">

                                    <a id="id_collapse" style="text-decoration: none;" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $cnt ?>" onclick="detectedCollapsed('collapse<?php echo $cnt ?>', 'opcionesPrograma<?php echo $cnt ?>', '<?php echo $objProg->getId(); ?>', '<?php echo $this->form; ?>')">
                                        <div class="panel-heading" style="background: #e6e7e8; height: 105px;  color: #033d7d;">
                                            <table style="width:100%;" >
                                                <tr>
                                                    <td style="width:150px;" rowspan="4" align="center">
                                                        <img src="<?php echo $_layoutParams['ruta_programas'].$objProg->getImagen(); ?>" height="100px" style="max-width: 130px;">
                                                    </td>
                                                    <td style="line-height: 16px; vertical-align:bottom;"><span name="tooltip_blo" style="color: #033d7d;" title="<?php echo $objProg->getNombre(); ?><br> Para mayor informaci&oacute;n haga click"><?php echo $objProg->getNombre(); ?></span></td>
                                                    <td style="line-height: 16px; font-size: 14px; width: 200px; vertical-align: bottom" align="right">
                                                        Valor Total Desde : <b name="tooltip_blo" title="<?php
                                                            for($i = 0; $i < 3; $i++) {
                                                                if (isset($OP_tipoHabi[$i]) && $OP_tipoHabi[$i] != '') {
                                                                    echo 'Habitacion '.($i+1).': ' . $OP_tipoHabi[$i] . '<br>';
                                                                }
                                                            }
                                                            ?>"><?php echo Functions::formatoValor($objProg->getMoneda(), $objProg->getPrecioDesde()); ?></b> <br>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td style="line-height: 12px; font-size: 12px; vertical-align: top;">
                                                        <b><?php echo ($objProg->getNoches()+1).' dias ' . $objProg->getNoches() . ' noches'; ?></b>
                                                        <br><span>Salida Desde :&nbsp;&nbsp;</span><b><?php if($objProg->getDesde()){echo Functions::invertirFecha($objProg->getDesde(), "/", "/");} ?></b></td>
                                                    <td rowspan="3" style="vertical-align: bottom; font-size: 13px; width: 200px; line-height: 12px;" align="right">
                                                        <input type="button" class="btn btn-primary btn-sm" style="margin-right:5px" value="Ver programa">
                                                    </td>
                                                </tr>
                                                
                                                <tr>
                                                    <td style="line-height: 15px; font-size: 12px;"><b>Precio total en base a</b> <?php $tmp=''; for($i = 0; $i < 3; $i++) {
                                                                if (isset($OP_tipoHabi[$i]) && $OP_tipoHabi[$i] != '') {
                                                                    echo $tmp.' Habitacion '.($i+1).': ' . $OP_tipoHabi[$i];
                                                                    $tmp='+';
                                                                }
                                                            } ?></td>
                                                </tr>
                                                
                                            </table>
                                            
                                            
                                            
                                            
                                        </div>
                                    </a>

                                    <div id="collapse<?php echo $cnt; ?>" class="panel-collapse collapse">
                                        <div class="panel-body">

                                            <div class="col-md-6" style="width:100%;">
                                                <div class="panel panel-grape" id="opcionesPrograma<?php echo $cnt; ?>">

                                                </div>


                                                <br>
                                                <div class="panel-body" style="border-top:1px solid #d2d3d6;">
                                                    <table>
                                                        <tr>
                                                            <td colspan="7" class="text-left">
                                                                <h4 style="color:#0085cc"><b>INCLUYE</b></h4>
                                                                <?php
                                                                $P_var_getIncluye = $objProg->getIncluye();
                                                                if ($P_var_getIncluye) {
                                                                    $xx = 0;
                                                                    $hh = 0;
                                                                    $P_ciudadHotel = NULL;
                                                                    $incluye = '';
                                                                    for ($i = 0; $i <= 5; $i++) {
                                                                        $P_arrayCiudadHotel[$i] = NULL;
                                                                    }
                                                                    //foreach($P_var_getIncluye as $columInclu)
                                                                    for ($i = 0; $i < count($P_var_getIncluye[0]); $i++) {
                                                                        if ($P_var_getIncluye[0][$i]->getCodigo() != 'CGO' && $P_var_getIncluye[0][$i]->getNombre() != '') {
                                                                            if ($P_var_getIncluye[0][$i]->getCiudad() != '') {
                                                                                $P_arrayCiudadHotel[$xx] = $P_var_getIncluye[0][$i]->getCiudad();
                                                                                $xx++;
                                                                            }

                                                                            if ($P_var_getIncluye[0][$i]->getCodigo() == 'HTL') {
                                                                                $P_ciudadHotel = " / " . $P_arrayCiudadHotel[$hh];
                                                                                $hh++;
                                                                            } else {
                                                                                $P_ciudadHotel = NULL;
                                                                            }

                                                                            if ($P_var_getIncluye[0][$i]->getNoches() < 10 && $P_var_getIncluye[0][$i]->getNoches() > 0) {
                                                                                $P_varNoches = "0" . $P_var_getIncluye[0][$i]->getNoches() . " Noches ";
                                                                            } else if ($P_var_getIncluye[0][$i]->getNoches() >= 10) {
                                                                                $P_varNoches = $P_var_getIncluye[0][$i]->getNoches() . " Noches ";
                                                                            } else {
                                                                                $P_varNoches = "";
                                                                            }

                                                                            $incluye.='<img  src="' . $_layoutParams['ruta_img'] . 'tick.png" width="12px" /> ' . $P_varNoches . $P_var_getIncluye[0][$i]->getNombre() . $P_ciudadHotel . "<br>";
                                                                        }
                                                                    }
                                                                }

                                                                echo $incluye;
                                                                ?>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </div>





                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel panel-default"></div>
                                <!-- </form> -->




        <?php
    }
} else {
    ?>
                            <div id="divAlertWarHot" class="alert alert-dismissable alert-warning" style="display:block;">
                                No se encontraron registros para esta busqueda.
                            </div>
<?php } ?> 

                    </div>
                </div>
            </div>

            <div class="modal-content alert-info" id="LoginStatus" style="position: fixed; left: 1%; top:90%; bottom: 5%; right: 210px; z-index: 9999;width: 160px; height: 65px; <?php if (!Session::get('Autenticado') || $this->form === 'a' || $this->form === '') {
    echo 'display: none;';
} ?>">
                <div class="modal-body" id="divLoginStatusIn" style="max-height: 400px; padding-top: 8px; ">
                    <table>
                        <tr><td>Usuario :</td><td><?php echo Session::get('sess_clave_usuario'); ?></td></tr>
                        <tr><td>Perfil : </td><td><?php echo Session::get('level'); ?></td></tr>
                    </table>
                </div>
            </div>
        </div> <!-- container -->
    </div> <!--wrap -->
</div> <!-- page-content -->
<script>
    $(document).ready(function () {

        $("[name$='tooltip_blo']").poshytip({className: "tip-darkgray", alignY: "top"});

    });
</script>