<script type="text/javascript" src="http://www.google.com/jsapi?key=AIzaSyByJ-PrjAq7ZDCa8_bCGYB-hzoAJcInrug"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>


<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">
            <ol class="breadcrumb">
                <li><a href="<?php echo BASE_URL . 'system'; ?>">Inicio</a></li>
                <li class="active">Busqueda de bloqueos</li>
            </ol>
            <h2 style="margin-left: 18px;">BLOQUEOS EN <b style="color:#FF9900;"><?php echo Session::get('sess_BP_ciudadDes'); ?></b></h2>

        </div>
        <div class="container">
            
            <div class="row">
                <div class="col-md-12">
                
                    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" id="btnCerrar1PRG" data-dismiss="modal" aria-hidden="true" style="display:block">&times;</button>
                                    <h4 class="modal-title" id="tituloFormPRG"></h4>
                                </div>
                                
                                <div class="modal-body" id="divPopupPRG"></div>
                                
                                <div class="modal-footer">
                                    <center>
                                        <a class="btn btn-primary"n href="<?php echo BASE_URL . Session::get('SESS_CONTROLLER').'/index/'.$this->form; ?>" id="btnAceptarPRG" style="display:none">Volver a reservar</a>
                                    </center>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div>
                    
                   <div class="modal-content" id="loginPopup" style="position: fixed; left: 485px; top:30%; bottom: 10%; right: 210px; z-index: 9999;width: 500px; height: 339px;display: none;">
                    <div class="modal-header">
                        <button type="button" class="close" id="btnCerrarLo" style="display:block" onclick="fadeOut('loginPopup');">&times;</button>
                        <h4 class="modal-title" id="tituloPopup">Login</h4>
                    </div>

                    <div class="modal-body" id="divLoginIn" style="max-height: 400px;  overflow-y: scroll;">
                        
                    </div>

                </div>
                    
                    
                    <div class="modal fade" id="myModalFotos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" id="btnCerrar1PRG" data-dismiss="modal" aria-hidden="true" style="display:block">&times;</button>
                                    <h4 class="modal-title" id="tituloFormFotos"></h4>
                                </div>
                                
                                <div class="modal-body" id="divPopupFotos"></div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div>
                    <div class="modal-content" id="condicionesPopup" style="position: fixed; left: 200px; top:10%; bottom: 10%; right: 210px; z-index: 9999; display: none;">
                    <div class="modal-header">
                        <button type="button" class="close" id="btnCerrarCon" style="display:block" onclick="fadeOut('condicionesPopup');fadeOut('detallePopup');">&times;</button>
                        <h4 class="modal-title" id="tituloPopup">Condiciones</h4>
                    </div>

                    <div class="modal-body" id="divPopupCon" style="max-height: 500px;  overflow-y: scroll;">
                        
                        
                    </div>
                    <!--<div class="modal-footer">
                        <center>
                            <table >
                                <tr>
                                    <td style="width: 20px;"><input type="checkbox" id="checkCondiciones"></td>
                                    <td>He leido y acepto las condiciones</td>
                                                                      
                                </tr>
                            </table>
                            <br>
                            <!--<table style="height: 30px; width: 219px;">
                                <tr>
                                <td><input type="button" class="btn btn-primary " id="aceptarCondiciones" onclick="Bloqueo.prototype.aceptarCondiciones();"value="Aceptar"></td>
                                    <td><input type="button"class="btn btn-primary  pull-right"onclick="fadeOut('condicionesPopup');fadeOut('detallePopup');$('#rP_btnProcesaRserva').prop('disabled',false);" value="Cancelar"></td>
                                </tr>
                            </table>
                        </center>
                    </div>-->
                </div>
                    
                    <div class="panel-group panel-info" id="accordion">
                    <?php
                    $cnt = 0;
                    if($this->objBloqueos) {
                        foreach($this->objBloqueos as $objProg) {
                            $cnt++;
                        ?>
                                        
                                            
 
                                              
                        <!-- <form class="frmOpcionesPRG_<?php echo $cnt; ?>"> -->
                            <div class="panel panel-default">
                                
                                <a id="id_collapse" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $cnt ?>" onclick="detectedCollapsed('collapse<?php echo $cnt ?>', 'opcionesPrograma<?php echo $cnt ?>', '<?php echo $objProg->getId(); ?>','<?php echo $this->form;?>')">
                                    <div class="panel-heading">
                                        <span style="float: left;">
                                            <img src="<?php echo $_layoutParams['ruta_img']; ?>down.png" width="12px">
                                        </span>
                                        <h4>&nbsp;&nbsp;&nbsp;<?php echo $objProg->getNombre(); ?></h4>
                                    </div>
                                </a>
                                
                                <div id="collapse<?php echo $cnt ?>" class="panel-collapse collapse">
                                    <div class="panel-body">

                                        <div class="col-md-6" style="width:100%;">
                                            <div class="panel panel-grape">
                                                <div class="panel-heading">
                                                        <h4> Salida: <?php echo Functions::invertirFecha($objProg->getDesde(), "/", "/"); ?> </h4>
                                                        <div class="options">
                                                                <i>
                                                                    <?php if($objProg->getNota()) { ?>
                                                                    
                                                                    <a data-toggle="modal" href="#myModal" 
                                                                    onClick="abrePopup('divPopupPRG', '<?php echo BASE_URL; ?>bloqueos/condicionesGenerales', 'tituloFormPRG', 'Condiciones generales', '<?php echo $objProg->getId(); ?>','<?php echo $this->form;?>');">
                                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>nota.png" width="24px" alt="Condiciones generales" title="Condiciones generales" />
                                                                    </a>
                                                                    
                                                                    <?php } if($objProg->getItiVuelo()) { ?>
                                                                    
                                                                    <a data-toggle="modal" href="#myModal" 
                                                                    onClick="abrePopup('divPopupPRG', '<?php echo BASE_URL;?>bloqueos/itinerarioVuelo', 'tituloFormPRG', 'Itinerario vuelo', '<?php echo $objProg->getId(); ?>','<?php echo $this->form;?>');">
                                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>avion.png" width="24px" alt="Itinerario de Vuelos" title="Itinerario de Vuelos" />
                                                                    </a>
                                                                    
                                                                    <?php } ?>
                                                                </i>
                                                        </div>
                                                </div>

                                                <div class="panel-body">
                                                    <div class="table-responsive">
                                                        <table class="table table-hover" style="margin-bottom: 0px;">
                                                            <thead>
                                                            <th style=" padding: 2px; ">Hotel</th>
                                                            <th style=" padding: 2px; width: 80px;">Categoria</th>
                                                            <th style=" padding: 2px; width: 80px;">Habitaci&oacute;n</th>
                                                            <th style=" padding: 2px; width: 90px;">P. Alimenticio</th>
                                                            <th></th>
                                                            <th></th>
                                                            <th width="58px" ></th>
                                                            </thead>
                                                            <tbody class="selects" id="opcionesPrograma<?php echo $cnt ?>">
                                                        
        
                                                                
     
                                                                
                                                            </tbody>
                                                            <tfoot>
                                                                <tr>
                                                                    <td colspan="7" class="text-left">
                                                                        <h4 style="color:#0085cc"><b>INCLUYE</b></h4>
                                                                        <?php
                                                                        $P_var_getIncluye= $objProg->getIncluye();
                                                                        if($P_var_getIncluye)
                                                                        {
                                                                            $xx=0;
                                                                            $hh=0;
                                                                            $P_ciudadHotel=NULL;
                                                                            $incluye='';
                                                                            for($i=0; $i<=5; $i++){$P_arrayCiudadHotel[$i]=NULL;}
                                                                            //foreach($P_var_getIncluye as $columInclu)
                                                                            for($i=0; $i<count($P_var_getIncluye[0]); $i++)
                                                                            {
                                                                                if($P_var_getIncluye[0][$i]->getCodigo()!='CGO' && $P_var_getIncluye[0][$i]->getNombre()!='')
                                                                                {
                                                                                    if($P_var_getIncluye[0][$i]->getCiudad()!='')
                                                                                    {
                                                                                        $P_arrayCiudadHotel[$xx]= $P_var_getIncluye[0][$i]->getCiudad();
                                                                                        $xx++;
                                                                                    }

                                                                                    if($P_var_getIncluye[0][$i]->getCodigo()=='HTL')
                                                                                    {
                                                                                        $P_ciudadHotel= " / ".$P_arrayCiudadHotel[$hh];
                                                                                        $hh++;
                                                                                    }
                                                                                    else
                                                                                    {
                                                                                        $P_ciudadHotel=NULL;
                                                                                    }

                                                                                    if($P_var_getIncluye[0][$i]->getNoches()<10 && $P_var_getIncluye[0][$i]->getNoches()>0)
                                                                                    {
                                                                                        $P_varNoches="0".$P_var_getIncluye[0][$i]->getNoches()." Noches ";
                                                                                    }
                                                                                    else if($P_var_getIncluye[0][$i]->getNoches()>=10)
                                                                                    {
                                                                                        $P_varNoches=$P_var_getIncluye[0][$i]->getNoches()." Noches ";
                                                                                    }
                                                                                    else
                                                                                    {
                                                                                        $P_varNoches="";
                                                                                    }

                                                                                    $incluye.='<img  src="'.$_layoutParams['ruta_img'].'tick.png" width="12px" /> '.$P_varNoches.$P_var_getIncluye[0][$i]->getNombre().$P_ciudadHotel."<br>";

                                                                                }
                                                                            }
                                                                        }
                                                                        
                                                                        echo $incluye;
                                                                        ?>
                                                                    </td>
                                                                </tr>

                                                            </tfoot>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default"></div>
                        <!-- </form> -->

                        
                        
                        
                    <?php 
                        }
                    } else { ?>
                        <div id="divAlertWarHot" class="alert alert-dismissable alert-warning" style="display:block;">
                        No se encontraron registros para esta busqueda.
                        </div>
                    <?php } ?> 
						
                    </div>
                </div>
            </div>
<div class="modal-content alert-info" id="LoginStatus" style="position: fixed; left: 1%; top:90%; bottom: 5%; right: 210px; z-index: 9999;width: 160px; height: 65px; <?php if(!Session::get('Autenticado')|| $this->form==='a' || $this->form===''){echo 'display: none;';}?>">
                   <div class="modal-body" id="divLoginStatusIn" style="max-height: 400px; padding-top: 8px; ">
                          <table>
                            <tr><td>Usuario :</td><td><?php echo Session::get('sess_clave_usuario');  ?></td></tr>
                            <tr><td>Perfil : </td><td><?php echo Session::get('level');  ?></td></tr>
                           </table>               
                    </div>

                </div>
        </div> <!-- container -->
    </div> <!--wrap -->
</div> <!-- page-content -->