<div ID="imprimirSector">
                            <html xmlns="http://www.w3.org/1999/xhtml">
                                <head>	
                                    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />	
                                    <title>Carta de confirmaci&oacute;n <?php echo $this->numFile; ?></title>	
                                    <style type="text/css"> 
                                        <!--
                                        .Base {font-family: Tahoma; font-size: 11px; color: #000000; }	
                                        .BorderColor {border-color:#E6E6E6; border-collapse:collapse}	
                                        .Cot {font-family: Tahoma; font-size: 17px; color: #000000}	
                                        .TopBot {font-family: Tahoma; font-size: 11px; color: #000000}	
                                        .PieTxt {font-family: Tahoma; font-size: 11px; color: #666666; text-align:justify}	
                                        .it {font-family: Tahoma; font-size: 9px; color: #666666; text-align:justify}	
                                        .NotaRojo {font-family: Tahoma; font-size: 15px; color: #990000; word-spacing:2px; line-height:15px}
                                        -->
                                    </style>
                                </head>
                                <body leftmargin="2" topmargin="2" marginwidth="2" marginheight="2" class="Base" >	 	
                                    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">	  
                                        <tr>
                                            <td align="left">
                                                <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>logo_tc.jpg"  height="100" vspace="5" border="0" />
                                            </td>
                                            <td width="50%" align="right" class="TopBot">
                                                <strong class="TopBot">
                                                Travel Club</strong><br />
                                                Av. Apoquindo #5555, piso 4, Las Condes<br />
                                                ventaonline@travelclub.cl<br /><br />	      
                                                <a href="http://www.travelclub.cl/" target="_blank"> http://www.travelclub.cl/ <br /></a>
                                                <br />
                                                Santiago, <?php echo Functions::convertirFechaCarta($this->CC_fecha);?>
                                            </td>


                                        </tr>	
                                    </table>	
                                    <br />

                                    <table width="100%" border="0" align="center" cellpadding="2" cellspacing="2" class="Base">
                                        <tr>
                                            <td height="60" colspan="3" align="center"><span class="Cot">Confirmaci&oacute;n de Compra Online</span></td>
                                        </tr>

                                        <tr>
                                            <td><strong>N&deg; Reserva</strong></td>
                                            <td>:</td>
                                            <td><?php echo $this->numFile;  ?></td>
                                        </tr>

                                        <tr>
                                            <td width="18%"><strong>Nombre Pagador</strong></td>
                                            <td width="2%">:</td>
                                            <td width="80%"><?php  echo str_replace('/', ' ', $this->CC_nomPax);?></td>
                                        </tr>
                                        <tr>
                                            <td width="18%">&nbsp;</td>
                                            <td width="2%">&nbsp;</td>
                                            <td width="80%">Email: <?php echo $this->CC_email . ', &nbsp;&nbsp;Tel&eacute;fono: ' . $this->CC_fono; ?></td>
                                        </tr>

                                        <!--<tr>
                                            <td width="18%"></td>
                                            <td width="2%"></td>
                                            <td width="80%">Tel&eacute;fono: 123123 &nbsp;&nbsp;-&nbsp;&nbsp; Mail: correo@dominio.cl</td>
                                        </tr>-->

                                        <tr>
                                            <td width="18%"><strong>N&deg; Pasajeros</strong></td>
                                            <td width="2%">:</td>
                                            <td width="80%"><?php echo $this->CC_nPax;  ?></td>
                                        </tr>

                                        <tr>
                                            <td><strong>Fecha Viaje </strong></td>
                                            <td>:</td>
                                            <td><?php echo $this->CC_fviaje;  ?></td>	  
                                        </tr>

                                        <tr>
                                            <td><strong>Programa </strong></td>
                                            <td>:</td>
                                            <td><?php echo $this->CC_nombreProg;  ?></td>	  
                                        </tr>

                                    </table>
                                    <br />
                                    
                                    <center><h3><u><b><font face="calibri"><a href="<?php echo BASE_URL;?>booking/voucher/<?php echo base64_encode($this->numFile);?>" target="_blank">Imprima sus Vouchers </a></font></b></u></h3></center>
                                        <hr noshade="noshade" />                                       </tr>
                                   

                                    <table width="100%" border="0" align="center" cellpadding="2" cellspacing="2" class="Base">
                                        <tr>
                                            <td colspan="3">De acuerdo a la solicitud de Reserva por Ud. efectuada, confirmo lo siguiente: </td>
                                        </tr>
                                        <tr>
                                            <td colspan="3"><hr noshade="noshade" /></td>
                                        </tr>
                                    </table>
                                    
                                    &nbsp; &nbsp; &nbsp; Incluye:<br />

                                    <table width="98%" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#E8E6E1">
                                        <tr>
                                            <td bordercolor="#FFFFFF">
                                                <table width="100%" border="0" cellpadding="2" cellspacing="2">	
                                                    <?php
                                                     if($this->CC_objsDetFile)
                                                      {
                                                      foreach($this->CC_objsDetFile as $objDF)
                                                      {
                                                      $s_1= $objDF->getPaxS();
                                                      $s_2= $objDF->getPaxD();
                                                      $s_3= $objDF->getPaxT();
                                                      $s_4= $objDF->getPaxQ();
                                                      $s_5= $objDF->getPaxA();
                                                      $s_6= $objDF->getPaxI();
                                                      $s_7= $objDF->getPaxC1();
                                                      $s_8= $objDF->getPaxCA();
                                                      $s_9= $objDF->getPaxC2();


                                                      /*if($row_detfile["pax_s"] <> "" && $row_detfile["pax_s"] <> "0")
                                                      $s_1 = intval($row_detfile["pax_s"]);
                                                      if($row_detfile["pax_d"] <> "" && $row_detfile["pax_d"] <> "0")
                                                      $s_2 = intval($row_detfile["pax_d"]);
                                                      if($row_detfile["pax_t"] <> "" && $row_detfile["pax_t"] <> "0")
                                                      $s_3 = intval($row_detfile["pax_t"]);
                                                      if($row_detfile["pax_q"] <> "" && $row_detfile["pax_q"] <> "0")
                                                      $s_4 = intval($row_detfile["pax_q"]);
                                                      if($row_detfile["pax_a"] <> "" && $row_detfile["pax_a"] <> "0")
                                                      $s_5 = intval($row_detfile["pax_a"]);
                                                      if($row_detfile["pax_i"] <> "" && $row_detfile["pax_i"] <> "0")
                                                      $s_6 = intval($row_detfile["pax_i"]);
                                                      if($row_detfile["pax_c"] <> "" && $row_detfile["pax_c"] <> "0")
                                                      $s_7 = intval($row_detfile["pax_c"]);
                                                      if($row_detfile["pax_ca"] <> "" && $row_detfile["pax_ca"] <> "0")
                                                      $s_8 = intval($row_detfile["pax_ca"]);
                                                      if($row_detfile["pax_c2"] <> "" && $row_detfile["pax_c2"] <> "0")
                                                      $s_9 = intval($row_detfile["pax_c2"]); */

                                                     $suma_total = $s_1 + $s_2 + $s_3 + $s_4 + $s_5 + $s_6 + $s_7 + $s_8 + $s_9 ;

                                                      echo '<tr>
                                                      <td width="50%" class="Base">
                                                      <strong>&middot;</strong>&nbsp; '/*.$suma_total.' Pax '*/.$objDF->getNombre().'<strong></strong>
                                                      </td>
                                                      <td width="10%" class="Base">';


                                                      if($objDF->getIn() != "01/01/1900" && $objDF->getOut() !='01/01/1900')
                                                      {
                                                      echo 'In : '.$objDF->getIn();
                                                      }
                                                      else
                                                      {
                                                      echo '';
                                                      }


                                                      echo '</td>
                                                      <td width="10%" class="Base">';


                                                      if($objDF->getOut() == "01/01/1900")
                                                      {
                                                      echo '';
                                                      }
                                                      else
                                                      {
                                                      echo 'Out : '.$objDF->getOut();
                                                      }


                                                      echo '</td></tr>';
                                                      }
                                                      }
                                                      else
                                                      {
                                                      echo '<tr><td>Error al cargar el incluye</td></tr>';
                                                      } 
                                                    ?>
                                                </table>
                                            </td>
                                        </tr>	
                                    </table>
                                    <br />


                                    <table width="98%" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#E8E6E1">
                                        <tr>
                                            <td bordercolor="#FFFFFF">
                                                <table width="100%" border="0" align="center" cellpadding="2" cellspacing="2" class="Base">
                                                 <?php $valorTotal = Functions::getTarifa(($this->CC_totventa + $this->CC_ajuste), 'P'); 
                                                      if ($this->CC_moneda == "D") {?>
                                                    <tr>
                                                        <td width="25%"><strong>&nbsp;Valor Total USD</strong></td>
                                                        <td>:</td>
                                                        <td width="75%">
                                                            <?php
                                                            if($this->CC_totventa)
                                                            {
                                                            //echo Functions::formatoValor($this->CC_moneda, $this->CC_totventa) . ' + ' .Functions::formatoValor($this->CC_moneda, $this->CC_ajuste).' (Impuestos)'; 
                                                             echo Functions::getTarifa(($this->CC_totventa + $this->CC_ajuste), $this->CC_moneda); //. ' (Impuestos Incluidos)'; 
                                                            }
                                                            ?>
                                                        </td>
                                                    </tr>

                                                    <tr>
                                                        <td width="25%"><strong>&nbsp;Tipo Cambio $ </strong></td>
                                                        <td width="2%">:</td>
                                                        <td width="75%"><?php echo $this->CC_cambio;  ?></td>
                                                    </tr>
                                                    <?php $valorTotal = Functions::getTarifa((($this->CC_totventa + $this->CC_ajuste)*$this->CC_cambio), 'P'); }  ?>

                                                    <tr>
                                                        <td width="25%"><strong>&nbsp;Valor Total $</strong></td>
                                                        <td width="2%">:</td>
                                                        <td width="75%"><?php echo $valorTotal;  ?> <!--(Impuestos Incluidos)--></td>
                                                    </tr>

                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                    <br />


                                    <b style="font-family: Tahoma; color: #000000; font-size: 12px; margin-left: 10px;">Detalle de Pasajeros</b>
                                    <table width="98%" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#E8E6E1">
                                        <tr>
                                            <td bordercolor="#FFFFFF">
                                                <table width="<?php if($this->CC_objsDetBloq[0]->getCantidadInf()>0) {?> 100% <?php }else{ ?> 50% <?php } ?>" border="0" cellpadding="2" cellspacing="2" class="Base">
                                                    <tr>
                                                        <th></th>
                                                        <th>Tipo</th>
                                                        <th>Nombre</th>
                                                        <th>Rut/Pasaporte</th>
                                                        <th>Fecha nacimiento</th>
                                                        <th><?php if($this->CC_objsDetBloq[0]->getCantidadInf()>0) {?>Nombre Infant <?php } ?></th>
                                                        <th><?php if($this->CC_objsDetBloq[0]->getCantidadInf()>0) {?>Rut Infant <?php } ?></th>
                                                        <th><?php if($this->CC_objsDetBloq[0]->getCantidadInf()>0) {?>Fecha nacimiento Infant <?php } ?></th>
                                                    </tr>
                                                    <?php
                                                    $contador = 1; 
                                                      if($this->CC_objsDetBloq)
                                                      {
                                                      foreach($this->CC_objsDetBloq as $objDB)
                                                      {
                                                      echo '<tr>
                                                      <td>'.$contador.'</td>
                                                      <td>';

                                                      if( strtoupper($objDB->getTipoPax()) == "A")
                                                      {
                                                      echo 'Adulto';
                                                      }
                                                      elseif(strtoupper($objDB->getTipoPax()) == "C")
                                                      {
                                                      echo 'Child';
                                                      }

                                                      echo '</td>
                                                      <td>'.str_replace('/', ' ', $objDB->getNomPax()).'</td>
                                                      <td>'.$objDB->getRut().'</td>
                                                      <td>';
                                                      if($objDB->getFChild() == "01/01/1900")
                                                      {
                                                      echo '';
                                                      }
                                                      else
                                                      {
                                                      echo $objDB->getFChild();
                                                      }

                                                      echo '</td>
                                                      <td>'.$objDB->getNInfant().'</td>
                                                      <td>'.$objDB->getRutInf().'</td>
                                                      <td>';

                                                      if($objDB->getFInfant() == "01/01/1900")
                                                      {
                                                      echo '';
                                                      }
                                                      else
                                                      {
                                                      echo $objDB->getFInfant();
                                                      }
                                                      echo '</td>
                                                      </tr>';

                                                      $contador = $contador + 1;
                                                      }
                                                      } 
                                                    ?>
                                                    <tr>
                                                        <td colspan="8" style="font-weight:bold;">&nbsp;</td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="8" style="font-weight:bold;">Itinerario de vuelo:</td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="8"><?php echo $this->CC_notas;  ?></td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>	
                                    </table>








                                    <br />
                                    <br />





                                    <!--<table width="100%" border="0" align="center" cellpadding="2" cellspacing="2" class="Base">

                                        <tr class="TopBot">
                                            <td colspan="3">DEPARTAMENTO RESERVA</td>
                                        </tr>
                                    </table>-->
                                    <br />	<br />






                                    <?php echo $this->condicionesGenerales;  ?>
                                    




                                    <style>
                                        <!--
                                        @media print{
                                            .oculto{display:none}
                                        }
                                        -->
                                    </style>
                                    <center>
                                        <div style="width:90%; text-align:right;" >
                                            <img class="oculto" src="<?php echo $_layoutParamsCB['ruta_img']; ?>print.png" onClick="javascript:imprSelec('imprimirSector')" width="32" style="cursor:pointer;" /> &nbsp;<br />&nbsp;
                                        </div>
                                    </center>
                                    <br /><br />
                                </body>

                            </html>
                        </div>
<script language="Javascript">
    function imprSelec(nombre)
    {
        var ficha = document.getElementById(nombre);
        var ventimp = window.open(' ', 'popimpr');
        ventimp.document.write( ficha.innerHTML );
        ventimp.document.close();
        ventimp.print( );
        ventimp.close();
    }
</script>