<div id="page-content" style="margin-top:55px;">
    <div id='wrap'>
        <div id="page-heading">
            <ol class="breadcrumb">
                <li><a href="">Inicio</a></li>
                <li class="active">Busqueda de bloqueos</li>
            </ol>
            <h3 style="margin-left: 18px;">&nbsp;&nbsp;</h3>

        </div>
        <div class="container">

            <div class="alert alert-dismissable alert-warning">
                Debe realizar una nueva busqueda.
            </div>

        </div>
    </div>
</div>