<?php 
foreach($this->DTH_objsDetTipoHab as $objFotosHotel) { 
    $publicFotos = ROOT . 'public' . DS . 'img' . DS . 'tipo_habitacion'. DS; 
    if( ($objFotosHotel->getFoto1() && file_exists($publicFotos.$objFotosHotel->getFoto1())) ||
        ($objFotosHotel->getFoto2() && file_exists($publicFotos.$objFotosHotel->getFoto2())) ||
        ($objFotosHotel->getFoto3() && file_exists($publicFotos.$objFotosHotel->getFoto3())) ||
        ($objFotosHotel->getFoto4() && file_exists($publicFotos.$objFotosHotel->getFoto4())) )
    {
        $active='class="active"';
        $item='active';
?>

<center>
    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="height: 370px;">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <?php if($objFotosHotel->getFoto1() && file_exists($publicFotos.$objFotosHotel->getFoto1())){?> 
    <li data-target="#myCarousel" data-slide-to="0" <?php echo $active; $active=''; ?>></li>
    <?php 
    }
    if($objFotosHotel->getFoto2() && file_exists($publicFotos.$objFotosHotel->getFoto2())){
    ?>
    <li data-target="#myCarousel" data-slide-to="1" <?php echo $active; $active=''; ?>></li>
    <?php 
    }
    if($objFotosHotel->getFoto3() && file_exists($publicFotos.$objFotosHotel->getFoto3())){
    ?>
    <li data-target="#myCarousel" data-slide-to="2" <?php echo $active; $active=''; ?>></li>
    <?php 
    }
    if($objFotosHotel->getFoto4() && file_exists($publicFotos.$objFotosHotel->getFoto4())){
    ?>
    <li data-target="#myCarousel" data-slide-to="3" <?php echo $active; $active=''; ?>></li>
    <?php 
    }
    ?>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
   
   <?php if($objFotosHotel->getFoto1() && file_exists($publicFotos.$objFotosHotel->getFoto1())){?> 
    <div class="item <?php echo $item; $item=''; ?>"> 
      <img src="<?php echo $_layoutParamsCB['ruta_fotos_hab'] . $objFotosHotel->getFoto1(); ?>" style="max-width: 587px; max-height: 384px;" alt="Foto Encabezado">
    </div>  
    <?php
    } 
    if($objFotosHotel->getFoto2() && file_exists($publicFotos.$objFotosHotel->getFoto2())){?>   
    <div class="item <?php echo $item; $item=''; ?>">
      <img src="<?php echo $_layoutParamsCB['ruta_fotos_hab'] . $objFotosHotel->getFoto2(); ?>" style="max-width: 587px; max-height: 384px;" alt="Foto 1">
    </div>
     
   <?php }
   if($objFotosHotel->getFoto3() && file_exists($publicFotos.$objFotosHotel->getFoto3())){?> 
    <div class="item <?php echo $item; $item=''; ?>">
      <img src="<?php echo $_layoutParamsCB['ruta_fotos_hab'] . $objFotosHotel->getFoto3(); ?>" style="max-width: 587px; max-height: 384px;" alt="Foto 2">
    </div>
    
    <?php }
    if($objFotosHotel->getFoto4() && file_exists($publicFotos.$objFotosHotel->getFoto4())){?>  
    <div class="item <?php echo $item; $item=''; ?>">
      <img src="<?php echo $_layoutParamsCB['ruta_fotos_hab'] . $objFotosHotel->getFoto4(); ?>" style="max-width: 587px; max-height: 384px;" alt="Foto 3">
    </div>
     
    <?php } ?>    
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" style="background-image: none;" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"><img src="<?php echo $_layoutParamsCB['ruta_img']; ?>leftCircle.png" width="30px" /></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" style="background-image: none;" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"><img src="<?php echo $_layoutParamsCB['ruta_img']; ?>rightCircle.png" width="30px" /></span>
    <span class="sr-only">Next</span>
  </a>
    </div></center>

<script type="text/javascript">

$(document).bind('keyup', function(e) {

  if(e.keyCode === 39){
    $('a.carousel-control.right').trigger('click');
  } else if(e.keyCode === 37){
  $('a.carousel-control.left').trigger('click');
  }

});

</script>

<?php } else { ?>
        No se encontraron fotos para este hotel.
<?php }
}?>