<?php
foreach($this->objMapa as $objMapa) {
    if($objMapa->getLat()) {?>
<script>
/*ICONO TSYACOM*/
var stockholm = new google.maps.LatLng(<?php echo $objMapa->getLat(); ?>, <?php echo $objMapa->getLon(); ?>);
var parliament = new google.maps.LatLng(<?php echo $objMapa->getLat(); ?>, <?php echo $objMapa->getLon(); ?>);
var marker;
var map;
var infowindow = new google.maps.InfoWindow();


/*ICONO TSYACOM*/
var beachMarker;
var image = RUTA_IMG_JS + 'ubicacion.png';
var tsyacomLatLng = new google.maps.LatLng(-33.425591, -70.613811);
var infoTsyacom = new google.maps.InfoWindow();


function initialize() {
    var mapOptions = {
        zoom: 15,
        center: stockholm
    };

    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);





    marker = new google.maps.Marker({
        map:map,
        draggable:true,
        animation: google.maps.Animation.DROP,
        position: parliament
    });
    google.maps.event.addListener(marker, 'click', toggleBounce);
    // Construct a new InfoWindow.
    var infowindow = new google.maps.InfoWindow({
        content: '<?php echo $objMapa->getHotel(); ?>'
    });
    // Opens the InfoWindow when marker is clicked.
    marker.addListener('click', function() {
        infowindow.open(map, marker);
    });
  
  
  
  
    beachMarker = new google.maps.Marker({
        position: tsyacomLatLng,
        map: map,
        animation: google.maps.Animation.DROP,
        icon: image
    });
    google.maps.event.addListener(beachMarker, 'click', toggleBounceTS);
    // Construct a new InfoWindow.
    var infoTsyacom = new google.maps.InfoWindow({
        content: 'TSYACOM'
    });
    // Opens the InfoWindow when marker is clicked.
    beachMarker.addListener('click', function() {
        infoTsyacom.open(map, beachMarker);
    });
}

function toggleBounce() {

  if (marker.getAnimation() != null) {
    marker.setAnimation(null);
  } else {
    marker.setAnimation(google.maps.Animation.BOUNCE);
  }
}

function toggleBounceTS() {

  if (beachMarker.getAnimation() != null) {
    beachMarker.setAnimation(null);
  } else {
    beachMarker.setAnimation(google.maps.Animation.BOUNCE);
  }
}
    google.maps.event.addDomListener(window, 'load', initialize());

</script>

<div id="map-canvas" style="width:100%; height:400px;"></div>
<?php } else { ?>
Este hotel no tiene asignado "Latitud" y "Longitud"
<?php }
} ?>