<?php
if ($this->objOpcBloqueos) {
    $cont = 0;
    $td=true;
    $open=true;
    $tmpRecordc=false;
    foreach ($this->objOpcBloqueos as $key=>$objOpcProg) { 
         
        if(($key+1) < $this->objOpcBloqueosCNT){
            $tmpRecordc = $this->objOpcBloqueos[($key+1)]->getRecordC();
        }
        
       
        ?>
            
        


    <?php if(($open) || ($objOpcProg->getRecordC() != $tmpRecordc)){ $open=false;  ?>
        <br>
        <div class="panel-heading">
            <h4> Salida: <?php echo Functions::invertirFecha($objOpcProg->getDesde(), "/", "/"); ?> </h4>
            <div class="options">
                    <i>
                        <?php if($objOpcProg->getNota()) { ?>

                        <a data-toggle="modal" href="#myModal" 
                        onClick="abrePopup('divPopupPRG', '<?php echo BASE_URL; ?>bloqueos/condicionesGenerales', 'tituloFormPRG', 'Condiciones generales', '<?php echo $objOpcProg->getId(); ?>','<?php echo $this->form;?>');">
                        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>nota.png" width="24px" alt="Condiciones generales" title="Condiciones generales" />
                        </a>

                        <?php } if($objOpcProg->getNota()) { ?>

                        <a data-toggle="modal" href="#myModal" 
                        onClick="abrePopup('divPopupPRG', '<?php echo BASE_URL; ?>bloqueos/condicionesGenerales', 'tituloFormPRG', 'Condiciones generales', '<?php echo $objOpcProg->getId(); ?>','<?php echo $this->form;?>');">
                        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>nota.png" width="24px" alt="Condiciones generales" title="Condiciones generales" />
                        </a>

                        <?php } if($objOpcProg->getItiVuelo()) { ?>

                        <a data-toggle="modal" href="#myModal" 
                        onClick="abrePopup('divPopupPRG', '<?php echo BASE_URL;?>bloqueos/itinerarioVuelo', 'tituloFormPRG', 'Itinerario vuelo', '<?php echo $objOpcProg->getId(); ?>','<?php echo $this->form;?>');">
                        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>avion.png" width="24px" alt="Itinerario de Vuelos" title="Itinerario de Vuelos" />
                        </a>

                        <?php } ?>
                    </i>
            </div>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table tabla-hover" style="margin-bottom: 0px; font-size: 12px;">
                    <thead style="background-color:#34495e; color: #FFFFFF">
                    <th style=" padding: 2px; text-align: center;">Hotel</th>
                    <th style=" padding: 2px; width: 80px; text-align: center;">Categ.</th>
                    <th style=" padding: 2px; width: 80px;">Habitaci&oacute;n</th>
                    <th style=" padding: 2px; width: 90px;">P. Alimenticio</th>
                    <th></th>
                    <th width="90px"></th>
                    <th width="58px" style=" padding: 2px;" ></th>
                    </thead>
                    <tbody class="selects">
    <?php }  ?>
                                                


                                                        
        
                                                                
     
                                                                
                                                            














        <?php
            $OP_hoteles = $objOpcProg->getHoteles();
            $OP_codHoteles = $objOpcProg->getCodHoteles();
            $OP_pa = $objOpcProg->getPA();
            $OP_th = $objOpcProg->getTH();
            $OP_codTh = $objOpcProg->getCodTH();
            $OP_cat = $objOpcProg->getCat();
            $OP_ciudad = $objOpcProg->getCiudad();
            $OP_planAli = $objOpcProg->getPlanAl();

            $OP_cntHoteles = count($objOpcProg->getHoteles());
            
            if($td){
                $td=false;
                $td_background='td-background1';
            } else {
                $td=true;
                $td_background='td-background2';
            }
            for ($i = 0; $i < $OP_cntHoteles; $i++) {
                $border_top='border-top-width: 0px;';
                if($i==0) { $border_top = '';}
                ?>
            <tr>
                <td class="<?php echo $td_background; ?>" style="color: #DF5F00; padding: 3px; vertical-align: middle; <?php echo $border_top; ?>">
                    <a name="tooltip_hotel"title='<?php echo $OP_ciudad[$i]; ?>'
                       style="opacity: 1;cursor:pointer; " 
                       data-toggle='modal' 
                       href='#myModal' 
                       onClick="fadeIn('detallePopup');
                               $('#divPopupPRG').css('overflow-y', 'scroll');
                               abrePopup('divPopupPRG', '<?php echo BASE_URL; ?>bloqueos/servicios', 'tituloFormPRG', '<?php echo $OP_hoteles[$i]; ?>', <?php echo $OP_codHoteles[$i] ?>, '<?php echo $this->form; ?>');"
                       id="tooltip_hotel_<?php //echo $objOpcProg->getClaveOpc(); ?>" ><?php echo $OP_hoteles[$i]; ?></a>
                </td>
                
                
                
                
                <!--<td style="padding: 2px; vertical-align: middle;"><?php echo $OP_ciudad[$i]; ?></td>-->
                <td class="<?php echo $td_background; ?>" style="padding: 3px; vertical-align: middle; <?php echo $border_top; ?>">
                    <?php
                    if (strlen($OP_cat[$i]) == 2) {
                        for ($j = 1; $j <= 5; $j++) {
                            if ($j <= substr($OP_cat[$i], 0, 1)) {
                                ?>
                                <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>star_on.png" height='12' title='Categoria' />
                            <?php } else { ?>
                                <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>star_off.png" height='12' title='Categoria' />   
                            <?php
                            }
                        }
                    } else {
                        echo $OP_cat[$i];
                    }
                    ?>
                </td>
                
                
                
                <td class="<?php echo $td_background; ?>" style="padding: 3px; vertical-align: middle; <?php echo $border_top; ?>" >
                    <a data-toggle='modal' href='#myModal' 
                       onClick=" abrePopupHab('divPopupPRG', '<?php echo BASE_URL; ?>bloqueos/fotosTipoHab', 'tituloFormPRG', 'Fotos Tipo Habitaci&oacute;n', '<?php echo $OP_codTh[$i]; ?>', <?php echo $OP_codHoteles[$i]; ?>, '<?php echo $this->form; ?>');">
                    <?php echo $OP_th[$i]; ?>
                    </a>
                </td>
                
                
                <td class="<?php echo $td_background; ?>" style="padding: 3px; vertical-align: middle; <?php echo $border_top; ?>" >
                    <a><?php echo $OP_planAli[$i]; ?></a>
                </td>
                
                
                <td class="<?php echo $td_background; ?>" width="100px" style="padding: 3px; vertical-align: middle; <?php echo $border_top; ?>">
                    <a data-toggle="modal" href="#myModal" 
                       onClick="fadeIn('detallePopup');
                               $('#divPopupPRG').css('overflow-y', 'scroll');
                               abrePopup('divPopupPRG', '<?php echo BASE_URL; ?>bloqueos/fotosHotel', 'tituloFormPRG', 'Fotos Hotel', <?php echo $OP_codHoteles[$i]; ?>, '<?php echo $this->form; ?>');">
                        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>foto.jpg" border='0' height='20' title='Fotos' />
                    </a>

                    <a data-toggle="modal" href="#myModal" 
                       onClick="fadeIn('detallePopup');
                               $('#divPopupPRG').css('overflow-y', 'scroll');
                               abrePopup('divPopupPRG', '<?php echo BASE_URL; ?>bloqueos/mapas', 'tituloFormPRG', 'Google Maps', <?php echo $OP_codHoteles[$i]; ?>, '<?php echo $this->form; ?>');" >
                        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>mapa.jpg" border='0' height='20' title='Mapa' />
                    </a>

                    <!--<a data-toggle='modal' href='#myModal' 
                        onClick="fadeIn('detallePopup'); $('#divPopupPRG').css('overflow-y', 'scroll'); abrePopup('divPopupPRG', '<?php echo BASE_URL; ?>bloqueos/servicios', 'tituloFormPRG', '<?php echo $OP_hoteles[$i]; ?>', <?php echo $OP_codHoteles[$i] ?>,'<?php echo $this->form; ?>');">
                        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>hotel.jpg" border='0' height='20' width="30" title='Hotel' />
                    </a>-->

            <?php if ($objOpcProg->getNotaOpc()) { ?>
                        <a data-toggle="modal" href="#myModal" 
                           onClick="abrePopup('divPopupPRG', '<?php echo BASE_URL; ?>bloqueos/notas', 'tituloFormPRG', 'Nota de opcion de programa', '<?php echo $objOpcProg->getIdOpc(); ?>', '<?php echo $this->form; ?>');">
                            <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>nota.png" width="20px" alt="Notas" title="Notas" />
                        </a>
            <?php } ?>
                </td>
            




                      <?php
                if($i==0) {
                    $OP_valores = $objOpcProg->getValorHab();
                    $OP_tipoHabi = $objOpcProg->getTipoHab();
                    ?>
            
            <td class="<?php echo $td_background; ?>" style="color:#F00; text-align:right; padding: 3px; vertical-align: middle;" rowspan="<?php echo $OP_cntHoteles; ?>">
                        <span name="tooltip_hotel" style="color:#F00; z-index:5; font-size: 14px; "title ='<?php
                                  if (isset($OP_tipoHabi[0]) && $OP_tipoHabi[0] != '') {
                                      echo 'Habitacion 1: ' . $OP_tipoHabi[0] . '<br>';
                                  }
                                  if (isset($OP_tipoHabi[1]) && $OP_tipoHabi[1] != '') {
                                      echo 'Habitacion 2: ' . $OP_tipoHabi[1] . '<br>';
                                  }
                                  if (isset($OP_tipoHabi[2]) && $OP_tipoHabi[2] != '') {
                                      echo 'Habitacion 3: ' . $OP_tipoHabi[2] . '<br>';
                                  }?>' >
                    <?php echo Functions::formatoValor($objOpcProg->getMoneda(), ($OP_valores[0] + $OP_valores[1] + $OP_valores[2])); ?>
                        </span>
                    </td>
                    <td class="<?php echo $td_background; ?>" rowspan="<?php echo $OP_cntHoteles; ?>" style=" vertical-align: middle; padding: 2px;">
                        <a data-toggle="modal"  <?php if ($this->form === 'a' || Session::get('sess_boton_pago') || Session::get('Autenticado')) {
                        echo'href="#myModal"';
                    } ?> 
                           onClick="openForm('divPopupPRG', '<?php echo BASE_URL; ?>bloqueos/reservaPrograma', 'tituloFormPRG', 'Formulario de reserva', '<?php echo $objOpcProg->getIdOpc(); ?>', '<?php echo $objOpcProg->getId(); ?>', '<?php echo $this->form; ?>');"
                           class="btn btn-primary resBloque btn-xs">Reservar</a>
                    </td>

                    </tr>
                    
                    <?php
                    $cont++;
                }
            }?>
            
            
            
            
            
            
            
            
            
            
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    <?php if($objOpcProg->getRecordC() != $tmpRecordc || $this->objOpcBloqueosCNT == ($key+1)){ ?>
                    </tbody>        
                        </table>
                    </div>
                </div>
                    <?php $open = true; }  ?>
                    
                    
                    
            
            
            
            
            
            
            
            
            
            
            
            
            <?php
    }
} else {
    ?>
    Ha ocurrido un error en la carga de opciones!
<?php } ?>
<script>
    $(document).ready(function () {
        
        $( "[name$='tooltip_hotel']" ).poshytip({ className: "tip-darkgray", alignY : "top" });

    });
</script>
