<?php
if($this->objOpcBloqueos) {
    foreach($this->objOpcBloqueos as $objOpcProg) {
    ?>

<tr>
    <td width="20px">
        <input type="radio" name="P_rdbOpcion" value="<?php echo $objOpcProg->getIdOpc(); ?>">
        <script type="text/javascript">
            $(function(){
                $( "#tooltip_hotel_<?php echo $objOpcProg->getIdOpc(); ?>" ).poshytip({ className: "tip-darkgray", alignY : "bottom" });
            });
        </script>
    </td>
    
    <?php
    $OP_hoteles= $objOpcProg->getHoteles();
    $OP_codHoteles= $objOpcProg->getCodHoteles();
    $OP_pa= $objOpcProg->getPA();
    $OP_th= $objOpcProg->getTH();
    $OP_codTh= $objOpcProg->getCodTH();
    $OP_cat= $objOpcProg->getCat();
    $OP_ciudad= $objOpcProg->getCiudad();

    $OP_cntHoteles = count($objOpcProg->getHoteles());
    for($i=0; $i<$OP_cntHoteles; $i++)
    {
    ?>
    <td>
        <?php 
            $_tittle = false;
            $_tittle = "<table align='center'  width='210px' style='background-color:#FFFFFF; border:2px solid #0085CC; vertical-align:top'>
            <tr>
                <td style='color:#FFFFFF; background-color:#0085CC' width='70px' align='center'>Fotos</td>
                <td style='color:#FFFFFF; background-color:#0085CC' width='70px' align='center'>Mapa</td>
                <td style='color:#FFFFFF; background-color:#0085CC' width='70px' align='center'>Servicios</td>
            </tr>

            <tr>	
                <td align='center'>
                    <a data-toggle='modal' href='#myModal' 
                        onClick='abrePopup(&quot;divPopupPRG&quot;, &quot;" . BASE_URL . "bloqueos/fotosHotel&quot;, &quot;tituloFormPRG&quot;, &quot;Fotos Hotel&quot;, $OP_codHoteles[$i]);' >
                    <img src='" . $_layoutParamsCB['ruta_img'] . "fotos.png' border='0' height='25' title='Fotos' />
                    </a>
                </td>
                <td align='center'>
                    <a data-toggle='modal' href='#myModal' 
                        onClick='abrePopup(&quot;divPopupPRG&quot;, &quot;" . BASE_URL . "bloqueos/mapas&quot;, &quot;tituloFormPRG&quot;, &quot;Google Maps&quot;, $OP_codHoteles[$i]);' >
                        <img src='" . $_layoutParamsCB['ruta_img'] . "ubicacion.png' border='0' height='26px' title='Mapa' />
                    </a>
                </td>
                <td align='center'>
                    <a data-toggle='modal' href='#myModal' 
                                onClick='abrePopup(&quot;divPopupPRG&quot;, &quot;" . BASE_URL . "bloqueos/servicios&quot;, &quot;tituloFormPRG&quot;, &quot;Todos los servicios&quot;, $OP_codHoteles[$i]);'>
                        <img src='" . $_layoutParamsCB['ruta_img'] . "servicios.png' border='0' height='27' title='Servicios' />
                    </a>
                </td>
            </tr>

            <tr>
                <td style='color:#FFFFFF; background-color:#0085CC' colspan='3' align='center'>Detalles Hotel</td>
            </tr>

            <tr>
                <td style='color:#000000;' colspan='3' align='left'>&nbsp;Categoria: <strong>$OP_cat[$i]</strong></td>
            </tr>                           
            <tr>
                <td style='color:#000000;' colspan='3' align='left'>
                    &nbsp;Tipo Habitaci&oacute;n:  <strong>$OP_th[$i]</strong>
                    <a data-toggle='modal' href='#myModal' 
                                onClick='abrePopup(&quot;divPopupPRG&quot;, &quot;" . BASE_URL . "system/fotosHotel&quot;, &quot;tituloFormPRG&quot;, &quot;Fotos Tipo Habitaci&oacute;n&quot;, 99999999999999);'>
                    <img src='".$_layoutParamsCB['ruta_img']."camara.png' align='bottom' border='0' width='16px' title='Fotos tipo habitaci&oacute;n' />
                    </a>
                </td>
            </tr>
            <tr>
                <td style='color:#000000;' colspan='3' align='left'>&nbsp;Plan Alimenticio: <strong>$OP_pa[$i]</strong></td>
            </tr>
            <tr>
                <td style='color:#000000;' colspan='3' align='left'>&nbsp;Ciudad Hotel: <strong>$OP_ciudad[$i]</strong></td>
            </tr>
        </table>"; ?>
        <a id="tooltip_hotel_<?php echo $objOpcProg->getIdOpc(); ?>"  style="cursor:pointer" title="<?php echo $_tittle; ?>"><?php echo $OP_hoteles[$i] ?></a>
    </td>
    <?php } 
    $OP_valores = $objOpcProg->getValorHab()
    ?>
    
    <td style="color:#F00;" width="105px"><?php echo Functions::formatoValor($objOpcProg->getMoneda(), ($OP_valores[0] + $OP_valores[1] + $OP_valores[2])); ?></td>
    <td width="24px">
        <?php if($objOpcProg->getNotaOpc()) { ?>
        <a data-toggle="modal" href="#myModal" 
        onClick="abrePopup('divPopupPRG', '<?php echo BASE_URL; ?>bloqueos/notas', 'tituloFormPRG', 'Nota de Programa', '<?php echo $objOpcProg->getIdOpc(); ?>');">
        <img src="<?php echo $_layoutParamsCB['ruta_img']; ?>nota.png" width="24px" alt="Notas" title="Notas" />
        </a>
        <?php } ?>
    </td>
</tr>
<?php 
    }
} else { ?>
Ha ocurrido un error en la carga de opciones!
<?php } ?>
