<?php
$incluyeArray = $this->objOpcionPrograma[0]->getIncluye();
if ($incluyeArray) {
    $xx = 0;
    $hh = 0;
    $P_ciudadHotel = NULL;
    $incluye = '';
    for ($i = 0; $i <= 5; $i++) {
        $P_arrayCiudadHotel[$i] = NULL;
    }
    
    for ($i = 0; $i < count($incluyeArray[0]); $i++) {
        if ($incluyeArray[0][$i]->getCodigo() != 'CGO' && $incluyeArray[0][$i]->getNombre() != '') {
            if ($incluyeArray[0][$i]->getCiudad() != '') {
                $P_arrayCiudadHotel[$xx] = $incluyeArray[0][$i]->getCiudad();
                $xx++; 
            }

            if ($incluyeArray[0][$i]->getCodigo() == 'HTL') {
                $P_ciudadHotel = " / " . $P_arrayCiudadHotel[$hh];
                $hh++;
            } else {
                $P_ciudadHotel = NULL;
            }

            if ($incluyeArray[0][$i]->getNoches() < 10 && $incluyeArray[0][$i]->getNoches() > 0) {
                $P_varNoches = "0" . $incluyeArray[0][$i]->getNoches() . " " /* " Noches " */;
            } else if ($incluyeArray[0][$i]->getNoches() >= 10) {
                $P_varNoches = $incluyeArray[0][$i]->getNoches() /* . " Noches " */;
            } else {
                $P_varNoches = "";
            }

            $incluye.= $P_varNoches . $incluyeArray[0][$i]->getNombre() . $P_ciudadHotel . "<br>";
        }
    }
}


Session::set('sess_descripcionServicioPRG', $this->objOpcionPrograma[0]->getNombre() . ": <br><br>" . $incluye);
?>
<script type="text/javascript">
    $('html').on('click', function (e) {
        if (typeof $(e.target).data('original-title') == 'undefined') {
            $('[data-original-title]').popover('hide');
            $('.popover.fade.top').css("display", "none", "important");
        }
    });

    $(function ()
    {
        $('[data-toggle="popover"]').popover({
            html: true
        });

<?php if ($this->botonPago) { ?>
            $("#txtNombre_pago").validaCampos('abcdefghijklmnñopqrstuvwxyz');
            $("#txtApellidos_pago").validaCampos('abcdefghijklmnñopqrstuvwxyz');
            $("#txtTelefono_pago").validaCampos('0123456789+-() ');
<?php } ?>
    });
</script>
<style>
    a .popover{
        max-width: 90%; /* Max Width of the popover (depending on the container!) */
        margin-left: -5%;
    }
    td > div > div.popover-content{
        height: 350px;
        overflow-y: scroll;
    }
</style>
<form enctype="multipart/form-data" class="frmReservaPRG">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h4>Detalle programa</h4>
        </div>
        <div class="panel-body">
            <div class="row">

                <div class="col-md-12">

                    <table align="center">
                        <tr>
                            <td><b>Programa</b>:</td>
                            <td><?php echo $this->objOpcionPrograma[0]->getCodigo() . ' - ' . $this->objOpcionPrograma[0]->getNombre(); ?> </td>
                        </tr>
                        <tr>
                            <td><b>Bloqueo</b>:</td>
                            <td> <?php echo $this->objOpcionPrograma[0]->getTramo(); ?></td>
                        </tr>
                        <tr>
                            <td><b>Salida</b>:</td>
                            <td> <?php echo $this->fechaSalida; ?></td>
                        </tr>
                        <tr>
                            <td><b>Hoteles</b>:</td>
                            <td>
                                <?php
                                for ($i = 0; $i < $this->hotelesCNT; $i++) {
                                    echo $this->hoteles[$i];
                                }
                                ?>
                            </td>
                        </tr>

                        <tr>
                            <td><br><b>Precio Total</b>:</td>
                            <td style="color:#F00;"><br> <b><?php echo '&nbsp;' . $this->precio; ?></b></td>
                        </tr>

                    </table>
                </div>

            </div>
        </div>
    </div>
    
    
    <?php if ($this->botonPago) { ?>
        <table class=" table table-bordered">
            <tr style="color: #fff; background-color: #2bbce0; border-color: #2bbce0;">
                <td colspan="4" align="center" style="padding:2px;">Datos de la Persona que efectúa la Reserva</td>
            </tr>

            <tr align="center" style="color: #fff; background-color: #2bbce0; border-color: #2bbce0; padding:2px;">
                <!--<td style="padding:2px;">Nombre</td>
                <td style="padding:2px;">Apellidos</td>-->
                <td style="padding:2px;">Email</td>
                <td style="padding:2px;">Teléfono</td>
            </tr>

            <tr align="center">
                <!-- <td><input type="text" name="txtNombre_pago" id="txtNombre_pago"></td>
                <td><input type="text" name="txtApellidos_pago" id="txtApellidos_pago"></td> -->
                <td><input type="text" name="txtEmail_pago" id="txtEmail_pago" class="form-control" maxlength="80" style="width:50%;"></td>
                <td><input type="text" name="txtTelefono_pago" id="txtTelefono_pago"class="form-control" maxlength="14" style="width:50%;"></td>
            </tr>

        </table>
    <?php } ?>



    <table class="table table-bordered">
        <tr style="color: #fff; background-color: #2bbce0; border-color: #2bbce0;">
            <td colspan="7" align="center" style="padding:2px;">Datos del Pasajero</td>
        </tr>

        <tr align="center" style="color: #fff; background-color: #2bbce0; border-color: #2bbce0; padding:2px;">
            <td style="padding:2px;">Tipo</td>
            <td style="padding:2px;">T.Pax</td>

            <td style="padding:2px;">Pasaporte</td>
            <td style="padding:2px;">Rut</td>
            <td style="padding:2px;">Nombre</td>
            <td style="padding:2px;">Apellidos</td>
            <td style="padding:2px;">Nacimiento</td>
        </tr>

        <?php
        $rP_cntRegistros = 1;
        Session::set('sessRP_cntPasajeros', 0);
        for ($i = 1; $i <= 3; $i++) {
            $rP_total_AC = 0;
            $rP_total_AC = Session::get("sess_BP_Adl_$i") + Session::get("sess_BP_Chd_$i");
            $rP_Edad_Child = 1;
            ?>
            <?php
            for ($x = 1; $x <= $rP_total_AC; $x++) {
                ?>
                <tr align="center">
                    <td>
                        <select name="rP_cmbTipoPax_<?php echo $rP_cntRegistros; ?>" id="rP_cmbTipoPax_<?php echo $rP_cntRegistros; ?>" style="width:60px;">
                            <?php
                            if (Session::get("sess_BP_Adl_$i") >= $x) {
                                ?>
                                <option selected="selected" value="A">Adl</option>
                                <?php
                            } else {
                                ?>
                                <option selected="selected" value="C">Ni&ntilde;o</option>
                                <?php
                            }
                            ?>
                        </select>
                    </td>
                    <td>
                        <select name="rP_cmbTratoPax_<?php echo $rP_cntRegistros; ?>" id="rP_cmbTratoPax_<?php echo $rP_cntRegistros; ?>" style="width:60px;">
                            <?php
                            if (Session::get("sess_BP_Adl_$i") >= $x) {
                                ?>
                                <option value="0">Mr</option>                
                                <option value="1">Mrs</option>
                                <option value="2">Mss</option>
                                <?php
                            } else {
                                ?>
                                <option value="3">Chl</option>
                                <?php
                            }
                            ?>
                        </select>
                    </td>

                    <td>
                        <input type="checkbox" id="rP_chkPas_<?php echo $rP_cntRegistros; ?>" name="rP_chkPas_<?php echo $rP_cntRegistros; ?>" >
                    </td>
                    <td>
                        <input  type="text" id="rP_txtRut_<?php echo $rP_cntRegistros; ?>" maxlength="15"
                                name="rP_txtRut_<?php echo $rP_cntRegistros; ?>" style="width:80px;">
                    </td>
                    <td>
                        <input   type="text" id="rP_txtNom_<?php echo $rP_cntRegistros; ?>" name="rP_txtNom_<?php echo $rP_cntRegistros; ?>" maxlength="25" style="width:100px;">
                    </td>
                    <td><input  type="text" id="rP_txtApe_<?php echo $rP_cntRegistros; ?>" name="rP_txtApe_<?php echo $rP_cntRegistros; ?>" maxlength="25" style="width:100px;"></td>
                    <td>
                        <script type="text/javascript">
                            $(function ()
                            {
                                
                                
                                $("#rP_txtNom_<?php echo $rP_cntRegistros; ?>").validaCampos('abcdefghijklmnñopqrstuvwxyz áéíóú');
                                $("#rP_txtApe_<?php echo $rP_cntRegistros; ?>").validaCampos('abcdefghijklmnñopqrstuvwxyz áéíóú');
                                
                                $("#rP_txtRut_<?php echo $rP_cntRegistros; ?>").validaCampos('abcdefghijklmnopqrstuvwxyz0123456789-');

                                $("#rP_FechaNac_<?php echo $rP_cntRegistros; ?>").datepicker({
                                changeMonth: true,
                                        changeYear: true,
                                        dateFormat: 'dd/mm/yy',
                                        firstDay: 1,
        <?php if (Session::get("sess_BP_Adl_$i") >= $x) { ?>
                                    maxDate: new Date(<?php echo $this->anoSalida - 12; ?>,<?php echo $this->mesSalida - 1; ?>,<?php echo $this->diaSalida; ?>),
                                            yearRange: "-100:+0",
            <?php
        } else {
            ?>
                                    maxDate: new Date(<?php echo $this->anoSalida - 2; ?>,<?php echo $this->mesSalida - 1; ?>,<?php echo $this->diaSalida; ?>),
                                            yearRange: "-<?php if (Session::get('sessRP_edadChd' . $rP_Edad_Child) != 0) {
                                                    echo Session::get('sessRP_edadChd' . $rP_Edad_Child) -1;
                                                    $rP_Edad_Child++;
            } else {
                echo '11';
            } ?>:+0",
            <?php
        }
        ?>

                                monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                                        'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                                        dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
                                        monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr',
                                            'May', 'Jun', 'Jul', 'Ago',
                                            'Sep', 'Oct', 'Nov', 'Dic']
                            });
                            });</script>
                        <input  type="text" id="rP_FechaNac_<?php echo $rP_cntRegistros; ?>" 
                                name="rP_FechaNac_<?php echo $rP_cntRegistros; ?>" style="width:80px;" readonly="readonly">
                    </td>
                </tr>
                <?php
                ++$rP_cntRegistros;
            }
        }
        Session::set('sessRP_cntPasajeros', $rP_cntRegistros);
        ?>

    </table>



<?php
if (Session::get('sess_BP_cntInf') > 0) {
    ?>
        <table class="table table-bordered">
            <tr style="color: #fff; background-color: #2bbce0; border-color: #2bbce0;">
                <td colspan="5" align="center" style="padding:2px;">Datos del Infante</td>
            </tr>

            <tr align="center" style="color: #fff; background-color: #2bbce0; border-color: #2bbce0;">
                <td style="padding:2px;">Pasaporte</td>
                <td style="padding:2px;">Rut</td>
                <td style="padding:2px;">Nombre</td>
                <td style="padding:2px;">Apellidos</td>
                <td style="padding:2px;">Nacimiento</td>
            </tr>

    <?php
    for ($i = 1; $i <= Session::get('sess_BP_cntInf'); $i++) {
        ?>
                <tr align="center">
                    <td><input type="checkbox" id="rP_chkPasInf_<?php echo $i; ?>" name="rP_chkPasInf_<?php echo $i; ?>"></td>
                    <td>
                        <input type="text" id="rP_txtRutInf_<?php echo $i; ?>" maxlength="10" 
                               name="rP_txtRutInf_<?php echo $i; ?>" style="width:80px;">
                    </td>
                    <td>
                        <input type="text" id="rP_txtNomInf_<?php echo $i; ?>" name="rP_txtNomInf_<?php echo $i; ?>" maxlength="15" style="width:100px;">
                    </td>
                    <td>
                        <input type="text" id="rP_txtApeInf_<?php echo $i; ?>" name="rP_txtApeInf_<?php echo $i; ?>" maxlength="15" style="width:100px;">
                    </td>
                    <td>
                        <script type="text/javascript">
                            $(function ()
                            {
                                $("#rP_txtNomInf_<?php echo $i; ?>").validaCampos('abcdefghijklmnñopqrstuvwxyz áéíóú');
                                $("#rP_txtApeInf_<?php echo $i; ?>").validaCampos('abcdefghijklmnñopqrstuvwxyz áéíóú');
                                $("#rP_txtRutInf_<?php echo $i; ?>").validaCampos('abcdefghijklmnopqrstuvwxyz0123456789-');

                                $("#rP_FechaNacInf_<?php echo $i; ?>").datepicker({
                                    changeMonth: true,
                                    changeYear: true,
                                    dateFormat: 'dd/mm/yy',
                                    firstDay: 1,
                                    //minDate: '-24m',
                                    minDate: new Date(<?php echo $this->anoSalida - 2; ?>,<?php echo $this->mesSalida - 1; ?>,<?php echo $this->diaSalida + 1; ?>),
                                    maxDate: '+0m',
                                    monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                                        'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                                    dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
                                    monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr',
                                        'May', 'Jun', 'Jul', 'Ago',
                                        'Sep', 'Oct', 'Nov', 'Dic'] //,
                                            //yearRange: "-2:+0"
                                });
                            });
                        </script>
                        <input type="text" id="rP_FechaNacInf_<?php echo $i; ?>" name="rP_FechaNacInf_<?php echo $i; ?>" style="width:90px;" readonly="readonly">
                    </td>
                </tr>
            <?php
        }
        ?>
        </table>
    <?php
}
?>


    <table class="table table-bordered" <?php if (Session::get('sess_boton_pago')) { ?>style="display:none;"<?php } ?>>
        <tr>
            <td>
                <textarea name="rP_txtComentario" id="rP_txtComentario" cols="50" rows="4" class="form-control" placeholder="Escribe un comentario..."></textarea>
            </td>
        </tr>
    </table>


    <br />
    <center>
        <table>
            <tr>
                <td>
                    <label style="cursor: pointer;"><input type="checkbox" id="checkCondiciones" name="checkCondiciones" onchange="Bloqueo.prototype.aceptarCondiciones();"/> He leido y acepto las</label>
                    <a href="#" data-toggle="popover" data-placement="top" title="Condiciones generales" data-content="<?php echo $this->condicionesGenerales; ?>">condiciones</a>
                    <input type="hidden" value="" id="QA" name="QA" >
                </td>
            </tr>
        </table>
    </center>
    <br>
    <center>
        <input type="button"  id="rP_btnProcesaRserva" class="btn btn-primary" value="<?php echo $this->boton; ?>" 
               onclick="Bloqueo.prototype.procesoReservaPRG('frmReservaPRG', '<?php echo BASE_URL ?>bloqueos/procesoReserva', 'rP_btnProcesaRserva', 'divPopupPRG', '<?php echo $this->form; ?>', '<?php echo BASE_URL ?>bloqueos/bloqueosCondiciones');
               ">
    </center>

</form>
<script>
    $(document).ready(function () {

        if (Bloqueo.prototype.B_aceptar_cond) {
            $("#checkCondiciones").prop('checked', true);
        }

        if (typeof window.event == 'undefined') {
            document.onkeypress = function (e) {
                var test_var = e.target.nodeName.toUpperCase();
                if (e.target.type)
                    var test_type = e.target.type.toUpperCase();
                if ((test_var == 'INPUT' && test_type == 'TEXT') || test_var == 'TEXTAREA') {
                    return e.keyCode;
                } else if (e.keyCode == 8) {
                    e.preventDefault();
                }
            }
        } else {
            document.onkeydown = function () {
                var test_var = event.srcElement.tagName.toUpperCase();
                if (event.srcElement.type)
                    var test_type = event.srcElement.type.toUpperCase();
                if ((test_var == 'INPUT' && test_type == 'TEXT') || test_var == 'TEXTAREA') {
                    return event.keyCode;
                } else if (event.keyCode == 8) {
                    event.returnValue = false;
                }
            }
        }
    });
</script> 